const newsItems = [
  {
    id: 1,
    url: "https://raw.githubusercontent.com/townlinksolutions/townlinksolutions/main/masthappna_naik/images/news/news1.jpg",
    titleEn: "Protest Against Sharavati Pumped Storage Project and River Diversion",
    titleKn: "ಶರಾವತಿ ಪಂಪ್ಡ್ ಸ್ಟೋರೇಜ್ ಯೋಜನೆ ಮತ್ತು ನದಿ ತಿರುವು ಯೋಜನೆಯ ವಿರುದ್ಧ ಪ್ರತಿಭಟನೆ",
    shortDescEn: "A report on the conclusion of a Padayatra (protest march) in Honnavar opposing the Sharavati Pumped Storage Project and river diversion, followed by a memorandum submission to the Tahsildar.",
    shortDescKn: "ಶರಾವತಿ ಪಂಪ್ಡ್ ಸ್ಟೋರೇಜ್ ಯೋಜನೆ ಮತ್ತು ನದಿ ತಿರುವು ಯೋಜನೆಯನ್ನು ವಿರೋಧಿಸಿ ಹೊನ್ನಾವರದಲ್ಲಿ ನಡೆದ ಪಾದಯಾತ್ರೆಯ ಸಮಾರೋಪ ಮತ್ತು ತಹಸೀಲ್ದಾರರಿಗೆ ಮನವಿ ಸಲ್ಲಿಸಿದ ವರದಿ.",
    contentEn: "The news article covers the successful conclusion of a Padayatra held in Honnavar, organized to oppose the implementation of the Sharavati Pumped Storage Project and proposed river linking projects. <strong>Key highlights from the report include:</strong> <strong>The Protest:</strong> Leaders and activists expressed that these projects are detrimental to the environment of Uttara Kannada. They emphasized that the district should be developed through eco-friendly tourism rather than destructive infrastructure. Masthappa Naik’s <strong>Address:</strong> Leading the movement, Masthappa Naik addressed the gathering at the Tahsildar's office, stating that a single protest is not enough and the struggle will continue until the government completely drops the Sharavati Pumped Storage Project. <strong>Community Support:</strong> The event saw participation from various religious and social figures, including Maruthi Guruji of Shri Kshetra Bangaramakki, who spoke about allowing the Sharavati River to flow naturally. <strong>Formal Action:</strong> A memorandum was formally submitted to Tahsildar Praveen Karande. Other notable attendees included farmer leader Ravi Patil, JDS leader Suraj Naik Soni, and several local representatives and environmentalists.",
    contentKn: "ಈ ಸುದ್ದಿ ಲೇಖನವು ಶರಾವತಿ ಪಂಪ್ಡ್ ಸ್ಟೋರೇಜ್ ಯೋಜನೆ ಮತ್ತು ಪ್ರಸ್ತಾವಿತ ನದಿ ಜೋಡಣೆ ಯೋಜನೆಗಳನ್ನು ವಿರೋಧಿಸಿ ಹೊನ್ನಾವರದಲ್ಲಿ ಆಯೋಜಿಸಲಾದ ಪಾದಯಾತ್ರೆಯ ಯಶಸ್ವಿ ಸಮಾರೋಪವನ್ನು ಒಳಗೊಂಡಿದೆ. ವರದಿಯ <br><br><strong>ಪ್ರಮುಖ ಅಂಶಗಳು:</strong><br> ಪ್ರತಿಭಟನೆ: ಈ ಯೋಜನೆಗಳು ಉತ್ತರ ಕನ್ನಡದ ಪರಿಸರಕ್ಕೆ ಹಾನಿಕಾರಕವೆಂದು ನಾಯಕರು ಮತ್ತು ಕಾರ್ಯಕರ್ತರು ವ್ಯಕ್ತಪಡಿಸಿದರು. ವಿನಾಶಕಾರಿ ಮೂಲಸೌಕರ್ಯಗಳಿಗಿಂತ ಪರಿಸರ ಸ್ನೇಹಿ ಪ್ರವಾಸೋದ್ಯಮದ ಮೂಲಕ ಜಿಲ್ಲೆಯನ್ನು ಅಭಿವೃದ್ಧಿಪಡಿಸಬೇಕೆಂದು ಅವರು ಒತ್ತಿ ಹೇಳಿದರು. ಮಾಸ್ತಪ್ಪ ನಾಯ್ಕ ಬಲಸೆ ಅವರ ಭಾಷಣ: ಚಳುವಳಿಯ ನೇತೃತ್ವ ವಹಿಸಿದ್ದ ಮಾಸ್ತಪ್ಪ ನಾಯ್ಕ ಬಲಸೆ ಅವರು ತಹಸೀಲ್ದಾರ್ ಕಚೇರಿಯಲ್ಲಿ ಮಾತನಾಡುತ್ತಾ, ಸರ್ಕಾರವು ಶರಾವತಿ ಪಂಪ್ಡ್ ಸ್ಟೋರೇಜ್ ಯೋಜನೆಯನ್ನು ಸಂಪೂರ್ಣವಾಗಿ ಕೈಬಿಡುವವರೆಗೆ ಹೋರಾಟ ಮುಂದುವರಿಯುತ್ತದೆ ಎಂದು ಹೇಳಿದರು. ಸಮುದಾಯದ ಬೆಂಬಲ: ಶ್ರೀ ಕ್ಷೇತ್ರ ಬಂಗಾರಮಕ್ಕಿಯ ಮಾರುತಿ ಗುರೂಜಿ ಸೇರಿದಂತೆ ವಿವಿಧ ಧಾರ್ಮಿಕ ಮತ್ತು ಸಾಮಾಜಿಕ ವ್ಯಕ್ತಿಗಳು ಭಾಗವಹಿಸಿದ್ದರು, ಅವರು ಶರಾವತಿ ನದಿಯನ್ನು ನೈಸರ್ಗಿಕವಾಗಿ ಹರಿಯಲು ಬಿಡಬೇಕೆಂದು ಮಾತನಾಡಿದರು. ಔಪಚಾರಿಕ ಕ್ರಮ: ತಹಸೀಲ್ದಾರ್ ಪ್ರವೀಣ್ ಕಾರಂಡೆ ಅವರಿಗೆ ಮನವಿಯನ್ನು ಸಲ್ಲಿಸಲಾಯಿತು. ರೈತ ನಾಯಕ ರವಿ ಪಾಟೀಲ್, ಜೆಡಿಎಸ್ ನಾಯಕ ಸೂರಜ್ ನಾಯಕ್ ಸೋನಿ ಮತ್ತು ಹಲವಾರು ಸ್ಥಳೀಯ ಪ್ರತಿನಿಧಿಗಳು ಮತ್ತು ಪರಿಸರವಾದಿಗಳು ಉಪಸ್ಥಿತರಿದ್ದರು.",
    category: "Sharavathi Project & Environmental Movement"
  },
  {
    id: 2,
    url: "https://raw.githubusercontent.com/townlinksolutions/townlinksolutions/main/masthappna_naik/images/news/news2.jpg",
    titleEn: "Environmental Advocacy and the Sharavathi River Protection Movement",
    titleKn: "ಪರಿಸರ ಪ್ರತಿಪಾದನೆ ಮತ್ತು ಶರಾವತಿ ನದಿ ಸಂರಕ್ಷಣಾ ಚಳುವಳಿ",
    shortDescEn: "Leading the 'Save the River' Padyatra to protect regional ecosystems.",
    shortDescKn: "ಪ್ರಾದೇಶಿಕ ಪರಿಸರ ವ್ಯವಸ್ಥೆಯನ್ನು ರಕ್ಷಿಸಲು 'ನದಿ ಉಳಿಸಿ' ಪಾದಯಾತ್ರೆಯ ನೇತೃತ್ವ.",
    contentEn: "This news clipping features Masthappa Naik leading a significant social and environmental movement in the Bhatkal-Honnavar constituency. The image documents his role as a key organizer of the 'Save the River' Padyatra, a grassroots march conducted to raise awareness and protest against the proposed Sharavathi Pumped Storage Project. The article details Masthappa's dedication to preserving the natural resources of Uttara Kannada. It highlights his transition from a successful industrialist to a community protector, showing him walking alongside local citizens to safeguard the regional ecosystem and the livelihoods dependent on the river. This image is a core piece of his personal brand, showcasing his courageous leadership and his deep-rooted commitment to environmental justice for the people of Murdeshwar and beyond.",
    contentKn: "ಈ ಸುದ್ದಿ ತುಣುಕು ಭಟ್ಕಳ-ಹೊನ್ನಾವರ ಕ್ಷೇತ್ರಗಳಲ್ಲಿ ಮಾಸ್ತಪ್ಪ ನಾಯ್ಕ ಬಲಸೆ ಅವರು ಪ್ರಮುಖ ಸಾಮಾಜಿಕ ಮತ್ತು ಪರಿಸರ ಚಳುವಳಿಯ ನೇತೃತ್ವ ವಹಿಸಿರುವುದನ್ನು ತೋರಿಸುತ್ತದೆ. ಪ್ರಸ್ತಾವಿತ ಶರಾವತಿ ಪಂಪ್ಡ್ ಸ್ಟೋರೇಜ್ ಯೋಜನೆಯ ವಿರುದ್ಧ ಜಾಗೃತಿ ಮೂಡಿಸಲು ಮತ್ತು ಪ್ರತಿಭಟಿಸಲು ನಡೆಸಿದ ತಳಮಟ್ಟದ ಪಾದಯಾತ್ರೆಯಾದ 'ನದಿ ಉಳಿಸಿ' ಪಾದಯಾತ್ರೆಯ ಪ್ರಮುಖ ಸಂಘಟಕರಾಗಿ ಅವರ ಪಾತ್ರವನ್ನು ಈ ಚಿತ್ರ ದಾಖಲಿಸುತ್ತದೆ. ಉತ್ತರ ಕನ್ನಡದ ನೈಸರ್ಗಿಕ ಸಂಪನ್ಮೂಲಗಳನ್ನು ಸಂರಕ್ಷಿಸಲು ಮಾಸ್ತಪ್ಪನವರ ಸಮರ್ಪಣೆಯನ್ನು ಲೇಖನವು ವಿವರಿಸುತ್ತದೆ. ಯಶಸ್ವಿ ಕೈಗಾರಿಕೋದ್ಯಮಿಯಿಂದ ಸಮುದಾಯದ ರಕ್ಷಕನಾಗಿ ಅವರ ಪರಿವರ್ತನೆಯನ್ನು ಇದು ಎತ್ತಿ ತೋರಿಸುತ್ತದೆ, ಪ್ರಾದೇಶಿಕ ಪರಿಸರ ವ್ಯವಸ್ಥೆಯನ್ನು ಮತ್ತು ನದಿಯನ್ನು ಅವಲಂಬಿಸಿರುವ ಜೀವನೋಪಾಯಗಳನ್ನು ರಕ್ಷಿಸಲು ಸ್ಥಳೀಯ ನಾಗರಿಕರೊಂದಿಗೆ ಅವರು ನಡೆಯುತ್ತಿರುವುದನ್ನು ತೋರಿಸುತ್ತದೆ. ಈ ಚಿತ್ರವು ಅವರ ವೈಯಕ್ತಿಕ ಬ್ರ್ಯಾಂಡ್‌ನ ಪ್ರಮುಖ ಭಾಗವಾಗಿದೆ, ಅವರ ಧೈರ್ಯಶಾಲಿ ನಾಯಕತ್ವವನ್ನು ಮತ್ತು ಮುರ್ಡೇಶ್ವರ ಮತ್ತು ಅದರಾಚೆಯ ಜನರಿಗಾಗಿ ಪರಿಸರ ನ್ಯಾಯಕ್ಕಾಗಿ ಅವರ ಆಳವಾದ ಬದ್ಧತೆಯನ್ನು ಪ್ರದರ್ಶಿಸುತ್ತದೆ.",
    category: "Sharavathi Project & Environmental Movement"
  },
  {
    id: 3,
    url: "https://raw.githubusercontent.com/townlinksolutions/townlinksolutions/main/masthappna_naik/images/news/news3.jpg",
    titleEn: "Promoting Values and Community Philanthropy",
    titleKn: "ಮೌಲ್ಯಗಳು ಮತ್ತು ಸಮುದಾಯದ ಲೋಕೋಪಕಾರವನ್ನು ಉತ್ತೇಜಿಸುವುದು",
    shortDescEn: "Engaging in philanthropic and educational initiatives for community upliftment.",
    shortDescKn: "ಸಮುದಾಯದ ಉನ್ನತಿಗಾಗಿ ಲೋಕೋಪಕಾರಿ ಮತ್ತು ಶೈಕ್ಷಣಿಕ ಉಪಕ್ರಮಗಳಲ್ಲಿ ತೊಡಗಿಸಿಕೊಳ್ಳುವುದು.",
    contentEn: "This news clipping captures Masthappa Naik engaged in his consistent philanthropic and educational initiatives within the Bhatkal-Honnavar region. The image depicts him during a public event—likely one of his organized Bhagavad Gita distribution drives or a student welfare program. The article highlights Masthappa’s commitment to moral education and supporting the younger generation. It focuses on his efforts to bridge professional success with social responsibility, showing him personally interacting with community members to provide direct aid and educational resources. This image reinforces his personal brand as a compassionate leader and mentor who is deeply invested in the spiritual and social upliftment of his community in Murdeshwar.",
    contentKn: "ಈ ಸುದ್ದಿ ತುಣುಕು ಭಟ್ಕಳ-ಹೊನ್ನಾವರ ಪ್ರದೇಶದಲ್ಲಿ ಮಾಸ್ತಪ್ಪ ನಾಯ್ಕ ಬಲಸೆ ಅವರು ತಮ್ಮ ನಿರಂತರ ಲೋಕೋಪಕಾರಿ ಮತ್ತು ಶೈಕ್ಷಣಿಕ ಉಪಕ್ರಮಗಳಲ್ಲಿ ತೊಡಗಿಸಿಕೊಂಡಿರುವುದನ್ನು ಸೆರೆಹಿಡಿದಿದೆ. ಈ ಚಿತ್ರವು ಸಾರ್ವಜನಿಕ ಕಾರ್ಯಕ್ರಮವೊಂದರಲ್ಲಿ ಅವರನ್ನು ಚಿತ್ರಿಸುತ್ತದೆ—ಬಹುಶಃ ಅವರು ಆಯೋಜಿಸಿದ ಭಗವದ್ಗೀತೆ ವಿತರಣಾ ಅಭಿಯಾನಗಳಲ್ಲಿ ಒಂದಾಗಿದೆ ಅಥವಾ ವಿದ್ಯಾರ್ಥಿ ಕಲ್ಯಾಣ ಕಾರ್ಯಕ್ರಮವಾಗಿದೆ. ಲೇಖನವು ನೈತಿಕ ಶಿಕ್ಷಣಕ್ಕೆ ಮತ್ತು ಯುವ ಪೀಳಿಗೆಯನ್ನು ಬೆಂಬಲಿಸಲು ಮಾಸ್ತಪ್ಪನವರ ಬದ್ಧತೆಯನ್ನು ಎತ್ತಿ ತೋರಿಸುತ್ತದೆ. ಇದು ವೃತ್ತಿಪರ ಯಶಸ್ಸನ್ನು ಸಾಮಾಜಿಕ ಜವಾಬ್ದಾರಿಯೊಂದಿಗೆ ಸೇತುವೆ ಮಾಡುವ ಅವರ ಪ್ರಯತ್ನಗಳ ಮೇಲೆ ಕೇಂದ್ರೀಕರಿಸುತ್ತದೆ, ನೇರ ಸಹಾಯ ಮತ್ತು ಶೈಕ್ಷಣಿಕ ಸಂಪನ್ಮೂಲಗಳನ್ನು ಒದಗಿಸಲು ಸಮುದಾಯದ ಸದಸ್ಯರೊಂದಿಗೆ ಅವರು ವೈಯಕ್ತಿಕವಾಗಿ ಸಂವಹನ ನಡೆಸುತ್ತಿರುವುದನ್ನು ತೋರಿಸುತ್ತದೆ. ಈ ಚಿತ್ರವು ಮುರ್ಡೇಶ್ವರದಲ್ಲಿನ ತಮ್ಮ ಸಮುದಾಯದ ಆಧ್ಯಾತ್ಮಿಕ ಮತ್ತು ಸಾಮಾಜಿಕ ಉನ್ನತಿಗಾಗಿ ಆಳವಾಗಿ ಹೂಡಿಕೆ ಮಾಡಿರುವ ಸಹಾನುಭೂತಿಯ ನಾಯಕ ಮತ್ತು ಮಾರ್ಗದರ್ಶಕರಾಗಿ ಅವರ ವೈಯಕ್ತಿಕ ಬ್ರ್ಯಾಂಡ್ ಅನ್ನು ಬಲಪಡಿಸುತ್ತದೆ.",
    category: "Cultural & Community Events"
  },
  {
    id: 4,
    url: "https://raw.githubusercontent.com/townlinksolutions/townlinksolutions/main/masthappna_naik/images/news/news4.jpg",
    titleEn: "Environmental Conservation Drive Gains Momentum",
    titleKn: "ಪರಿಸರ ಸಂರಕ್ಷಣಾ ಅಭಿಯಾನಕ್ಕೆ ವೇಗ",
    shortDescEn: "Masthappa Naik joins hands with local youth for a greener future.",
    shortDescKn: "ಹಸಿರು ಭವಿಷ್ಯಕ್ಕಾಗಿ ಮಾಸ್ತಪ್ಪ ನಾಯ್ಕ ಬಲಸೆ ಸ್ಥಳೀಯ ಯುವಕರೊಂದಿಗೆ ಕೈಜೋಡಿಸಿದ್ದಾರೆ.",
    contentEn: "A massive tree-planting drive was initiated by Masthappa Naik to combat deforestation and promote environmental awareness among the younger generation.",
    contentKn: "ಅರಣ್ಯನಾಶದ ವಿರುದ್ಧ ಹೋರಾಡಲು ಮತ್ತು ಯುವ ಪೀಳಿಗೆಯಲ್ಲಿ ಪರಿಸರ ಜಾಗೃತಿ ಮೂಡಿಸಲು ಮಾಸ್ತಪ್ಪ ನಾಯ್ಕ ಬಲಸೆ ಅವರು ಬೃಹತ್ ವೃಕ್ಷಾರೋಪಣ ಅಭಿಯಾನವನ್ನು ಪ್ರಾರಂಭಿಸಿದರು.",
    category: "Sharavathi Project & Environmental Movement"
  },
  {
    id: 5,
    url: "https://raw.githubusercontent.com/townlinksolutions/townlinksolutions/main/masthappna_naik/images/news/news5.jpg",
    titleEn: "Masthappa Naik Honored with 'Bharat Industrial Icon' Award",
    titleKn: "ಮಾಸ್ತಪ್ಪ ನಾಯ್ಕ ಬಲಸೆ ಅವರಿಗೆ 'ಭಾರತ ಕೈಗಾರಿಕಾ ಐಕಾನ್' ಪ್ರಶಸ್ತಿ",
    shortDescEn: "Honnavar entrepreneur Masthappa Naik Balase was honored with the \"Bharat Industrial Icon\" award at a ceremony held in Chennai. The award recognizes his innovation in the industrial sector, his social responsibility, and his role in inspiring the youth.",
    shortDescKn: "ಹೊನ್ನಾವರದ ಉದ್ಯಮಿ ಮಾಸ್ತಪ್ಪ ನಾಯ್ಕ ಬಲಸೆ ಅವರಿಗೆ ಚೆನ್ನೈನಲ್ಲಿ ನಡೆದ ಸಮಾರಂಭದಲ್ಲಿ \"ಭಾರತ ಕೈಗಾರಿಕಾ ಐಕಾನ್\" ಪ್ರಶಸ್ತಿಯನ್ನು ನೀಡಿ ಗೌರವಿಸಲಾಯಿತು. ಈ ಪ್ರಶಸ್ತಿಯು ಕೈಗಾರಿಕಾ ಕ್ಷೇತ್ರದಲ್ಲಿನ ಅವರ ನಾವೀನ್ಯತೆ, ಸಾಮಾಜಿಕ ಜವಾಬ್ದಾರಿ ಮತ್ತು ಯುವಕರಿಗೆ ಸ್ಫೂರ್ತಿ ನೀಡುವ ಅವರ ಪಾತ್ರವನ್ನು ಗುರುತಿಸುತ್ತದೆ.",
    contentEn: "The Award: Masthappa Naik received the \"Bharat Industrial Icon\" (Bharat Kaigarika Icon) award during an event held on a Wednesday in Chennai.\n\nReasons for Recognition: The selection committee cited several key factors for this honor:\nInnovation: His \"newness\" and creative approach within the industrial field.\nSocial Responsibility: Balancing business success with a commitment to societal welfare.\nYouth Inspiration: Serving as a role model and motivating the younger generation to excel in entrepreneurship.\n\nDual Role (Activist & Entrepreneur): The report explicitly connects his business success to his public activism. It mentions that while he is an \"Industrial Icon,\" he remains at the forefront of major local struggles, specifically:\nOpposing the Sharavati Pumped Storage Project.\nLeading the demand for the establishment of a Multi-Specialty Hospital in the district.\n\nSignificance: This recognition provides a well-rounded view of Masthappa Naik, proving he is not just a critic of government policies but also a recognized contributor to the economy and a respected figure on a national level.",
    contentKn: "ಪ್ರಶಸ್ತಿ: ಚೆನ್ನೈನಲ್ಲಿ ಬುಧವಾರ ನಡೆದ ಕಾರ್ಯಕ್ರಮದಲ್ಲಿ ಉದ್ಯಮಿ ಮಾಸ್ತಪ್ಪ ನಾಯ್ಕ ಬಲಸೆ ಅವರಿಗೆ 'ಭಾರತ ಕೈಗಾರಿಕಾ ಐಕಾನ್' ಪ್ರಶಸ್ತಿಯನ್ನು ಪ್ರದಾನ ಮಾಡಲಾಯಿತು.\n\nಗುರುತಿಸುವಿಕೆಯ ಕಾರಣಗಳು: ಆಯ್ಕೆ ಸಮಿತಿಯು ಈ ಗೌರವಕ್ಕಾಗಿ ಹಲವಾರು ಪ್ರಮುಖ ಅಂಶಗಳನ್ನು ಉಲ್ಲೇಖಿಸಿದೆ:\nನಾವೀನ್ಯತೆ: ಕೈಗಾರಿಕಾ ಕ್ಷೇತ್ರದಲ್ಲಿ ಅವರ \"ಹೊಸತನ\" ಮತ್ತು ಸೃಜನಶೀಲ ವಿಧಾನ.\nಸಾಮಾಜಿಕ ಜವಾಬ್ದಾರಿ: ವ್ಯವಹಾರದ ಯಶಸ್ಸನ್ನು ಸಾಮಾಜಿಕ ಕಲ್ಯಾಣದ ಬದ್ಧತೆಯೊಂದಿಗೆ ಸಮತೋಲನಗೊಳಿಸುವುದು.\nಯುವ ಸ್ಫೂರ್ತಿ: ಉದ್ಯಮಶೀಲತೆಯಲ್ಲಿ ಯುವ ಪೀಳಿಗೆಯು ಉತ್ತಮ ಸಾಧನೆ ಮಾಡಲು ಮಾದರಿಯಾಗಿ ಸೇವೆ ಸಲ್ಲಿಸುವುದು.\n\nದ್ವಿತೀಯ ಪಾತ್ರ (ಕಾರ್ಯಕರ್ತ ಮತ್ತು ಉದ್ಯಮಿ): ವರದಿಯು ಅವರ ವ್ಯವಹಾರದ ಯಶಸ್ಸನ್ನು ಅವರ ಸಾರ್ವಜನಿಕ ಕ್ರಿಯಾಶೀಲತೆಯೊಂದಿಗೆ ಸ್ಪಷ್ಟವಾಗಿ ಸಂಪರ್ಕಿಸುತ್ತದೆ. ಅವರು \"ಕೈಗಾರಿಕಾ ಐಕಾನ್\" ಆಗಿದ್ದರೂ, ಅವರು ಪ್ರಮುಖ ಸ್ಥಳೀಯ ಹೋರಾಟಗಳ ಮುಂಚೂಣಿಯಲ್ಲಿದ್ದಾರೆ ಎಂದು ಅದು ಉಲ್ಲೇಖಿಸುತ್ತದೆ, ನಿರ್ದಿಷ್ಟವಾಗಿ:\nಶರಾವತಿ ಪಂಪ್ಡ್ ಸ್ಟೋರೇಜ್ ಯೋಜನೆಯ ವಿರೋಧ.\nಜಿಲ್ಲೆಯಲ್ಲಿ ಮಲ್ಟಿ ಸ್ಪೆಷಾಲಿಟಿ ಆಸ್ಪತ್ರೆ ಸ್ಥಾಪನೆಗೆ ಆಗ್ರಹ.\n\nಮಹತ್ವ: ಈ ಮನ್ನಣೆಯು ಮಾಸ್ತಪ್ಪ ನಾಯ್ಕ ಬಲಸೆ ಅವರ ಸಮಗ್ರ ನೋಟವನ್ನು ಒದಗಿಸುತ್ತದೆ, ಅವರು ಕೇವಲ ಸರ್ಕಾರಿ ನೀತಿಗಳ ಟೀಕಾಕಾರರಲ್ಲ, ಬದಲಾಗಿ ಆರ್ಥಿಕತೆಗೆ ಗುರುತಿಸಲ್ಪಟ್ಟ ಕೊಡುಗೆದಾರರು ಮತ್ತು ರಾಷ್ಟ್ರೀಯ ಮಟ್ಟದಲ್ಲಿ ಗೌರವಾನ್ವಿತ ವ್ಯಕ್ತಿ ಎಂದು ಸಾಬೀತುಪಡಿಸುತ್ತದೆ.",
    category: "Cultural & Community Events"
  },
  {
    id: 6,
    url: "https://raw.githubusercontent.com/townlinksolutions/townlinksolutions/main/masthappna_naik/images/news/news6.jpg",
    titleEn: "Youth Leadership Summit in Bhatkal",
    titleKn: "ಭಟ್ಕಳದಲ್ಲಿ ಯುವ ನಾಯಕತ್ವ ಶೃಂಗಸಭೆ",
    shortDescEn: "Inspiring the next generation of leaders.",
    shortDescKn: "ಮುಂದಿನ ಪೀಳಿಗೆಯ ನಾಯಕರನ್ನು ಪ್ರೇರೇಪಿಸುವುದು.",
    contentEn: "Masthappa Naik addressed a gathering of young leaders, emphasizing the importance of integrity, hard work, and community service in building a better society.",
    contentKn: "ಉತ್ತಮ ಸಮಾಜವನ್ನು ನಿರ್ಮಿಸುವಲ್ಲಿ ಪ್ರಾಮಾಣಿಕತೆ, ಕಠಿಣ परिश्रम ಮತ್ತು ಸಮುದಾಯ ಸೇವೆಯ ಪ್ರಾಮುಖ್ಯತೆಯನ್ನು ಒತ್ತಿಹೇಳುತ್ತಾ ಮಾಸ್ತಪ್ಪ ನಾಯ್ಕ ಬಲಸೆ ಅವರು ಯುವ ನಾಯಕರ ಸಭೆಯನ್ನು ಉದ್ದೇಶಿಸಿ ಮಾತನಾಡಿದರು.",
    category: "Youth Lead"
  },
  {
    id: 7,
    url: "https://raw.githubusercontent.com/townlinksolutions/townlinksolutions/main/masthappna_naik/images/news/news7.jpg",
    titleEn: "Infrastructure Projects Fast-Tracked",
    titleKn: "ಮೂಲಸೌಕರ್ಯ ಯೋಜನೆಗಳಿಗೆ ವೇಗ",
    shortDescEn: "Improving connectivity and basic amenities in the region.",
    shortDescKn: "ಈ ಪ್ರದೇಶದಲ್ಲಿ ಸಂಪರ್ಕ ಮತ್ತು ಮೂಲಭೂತ ಸೌಕರ್ಯಗಳ ಸುಧಾರಣೆ.",
    contentEn: "Several key infrastructure projects, including road repairs and water supply systems, have been fast-tracked under the guidance of Masthappa Naik.",
    contentKn: "ರಸ್ತೆ ದುರಸ್ತಿ ಮತ್ತು ನೀರು ಸರಬರಾಜು ವ್ಯವಸ್ಥೆ ಸೇರಿದಂತೆ ಹಲವಾರು ಪ್ರಮುಖ ಮೂಲಸೌಕರ್ಯ ಯೋಜನೆಗಳನ್ನು ಮಾಸ್ತಪ್ಪ ನಾಯ್ಕ ಬಲಸೆ ಅವರ ಮಾರ್ಗದರ್ಶನದಲ್ಲಿ ವೇಗಗೊಳಿಸಲಾಗಿದೆ.",
    category: "Administrative Engagement"
  },
  {
    id: 8,
    url: "https://raw.githubusercontent.com/townlinksolutions/townlinksolutions/main/masthappna_naik/images/news/news8.jpg",
    titleEn: "Masthappa Naik Accuses Influential Politician of Illegal Land Grabbing",
    titleKn: "ಪ್ರಭಾವಿ ರಾಜಕಾರಣಿಯಿಂದ ಸರ್ಕಾರಿ ಭೂಮಿ ಕಬಳಿಕೆ: ಮಾಸ್ತಪ್ಪ ನಾಯ್ಕ ಬಲಸೆ ಗಂಭೀರ ಆರೋಪ",
    shortDescEn: "Social activist Masthappa Naik has accused an influential politician from the Bhatkal-Honnavar constituency of operating a \"Land Mafia\" to illegally transfer four acres of government land in Prabhat Nagar into the names of four private individuals.",
    shortDescKn: "ಸಾಮಾಜಿಕ ಕಾರ್ಯಕರ್ತ ಮಾಸ್ತಪ್ಪ ನಾಯ್ಕ ಬಲಸೆ ಅವರು ಭಟ್ಕಳ-ಹೊನ್ನಾವರ ಕ್ಷೇತ್ರದ ಪ್ರಭಾವಿ ರಾಜಕಾರಣಿಯೊಬ್ಬರು ಹೊನ್ನಾವರದ ಪ್ರಭಾತ ನಗರದಲ್ಲಿ ನಾಲ್ಕು ಎಕರೆ ಸರ್ಕಾರಿ ಭೂಮಿಯನ್ನು \"ಲ್ಯಾಂಡ್ ಮಾಫಿಯಾ\" ಮೂಲಕ ನಾಲ್ಕು ಖಾಸಗಿ ವ್ಯಕ್ತಿಗಳ ಹೆಸರಿಗೆ ಅಕ್ರಮವಾಗಿ ವರ್ಗಾಯಿಸಿದ್ದಾರೆ ಎಂದು ಆರೋಪಿಸಿದ್ದಾರೆ.",
    contentEn: "The Core Allegation: Naik alleges that highly valuable government land (worth approximately ₹50 Crores) has been \"looted\" by a powerful local politician who used threats and influence to manipulate government officials.\n\nProperty Details: Location: Prabhat Nagar, Honnavar Town. Survey Numbers: 238 and 239. Area: 4 Acres.\n\nLegal Background: The report states that this specific land was legally confirmed as government property twice in the past—once in 1974 and again in 2004.\n\nThe \"Scam\" Timeline: According to Naik, on January 12, 2026, the Land Tribunal issued an order granting this land to four individuals. He claims the politician pressured and intimidated officials to ensure this illegal allotment took place.\n\nSocial Justice Concern: Naik pointed out the hypocrisy of the system, noting that while poor people who have been cultivating small plots of land for years are denied official sanctions, \"mafia\" groups are granted prime government land within days through political clout.\n\nAction Plan: During the conference at Sagar Residency, Naik displayed copies of the land orders and announced that he would be approaching the court to challenge this illegal allotment and ensure the land is returned for public use.\n\nKey Witnesses: The press meet was supported by several local figures, including Dinesh Madiwala, Bhaskar Devadiga, Yogesh Shetty, and others.",
    contentKn: "ಪ್ರಮುಖ ಆರೋಪ: ಸುಮಾರು ₹50 ಕೋಟಿ ಮೌಲ್ಯದ ಅತ್ಯಂತ ಬೆಲೆಬಾಳುವ ಸರ್ಕಾರಿ ಭೂಮಿಯನ್ನು ಪ್ರಭಾವಿ ಸ್ಥಳೀಯ ರಾಜಕಾರಣಿಯೊಬ್ಬರು ಬೆದರಿಕೆ ಮತ್ತು ಪ್ರಭಾವ ಬಳಸಿ ಸರ್ಕಾರಿ ಅಧಿಕಾರಿಗಳನ್ನು ಮ್ಯಾನಿಪ್ಯುಲೇಟ್ ಮಾಡುವ ಮೂಲಕ \"ಲೂಟಿ\" ಮಾಡಿದ್ದಾರೆ ಎಂದು ನಾಯ್ಕ್ ಆರೋಪಿಸಿದ್ದಾರೆ.\n\nಭೂಮಿಯ ವಿವರಗಳು: ಸ್ಥಳ: ಪ್ರಭಾತ ನಗರ, ಹೊನ್ನಾವರ ಪಟ್ಟಣ. ಸರ್ವೆ ನಂಬರ್: 238 ಮತ್ತು 239. ವಿಸ್ತೀರ್ಣ: 4 ಎಕರೆ.\n\nಕಾನೂನು ಹಿನ್ನೆಲೆ: ಈ ನಿರ್ದಿಷ್ಟ ಭೂಮಿಯನ್ನು ಹಿಂದೆ ಎರಡು ಬಾರಿ - ಒಮ್ಮೆ 1974 ರಲ್ಲಿ ಮತ್ತು ಮತ್ತೊಮ್ಮೆ 2004 ರಲ್ಲಿ ಅಧಿಕೃತವಾಗಿ ಸರ್ಕಾರಿ ಆಸ್ತಿ ಎಂದು ದೃಢಪಡಿಸಲಾಗಿದೆ ಎಂದು ವರದಿ ತಿಳಿಸಿದೆ.\n\n\"ಹಗರಣದ\" ಕಾಲಾವಧಿ: ನಾಯ್ಕ್ ಅವರ ಪ್ರಕಾರ, ಜನವರಿ 12, 2026 ರಂದು, ಭೂ ನ್ಯಾಯ ಮಂಡಳಿಯು ಈ ಭೂಮಿಯನ್ನು ನಾಲ್ಕು ವ್ಯಕ್ತಿಗಳಿಗೆ ಮಂಜೂರು ಮಾಡುವ ಆದೇಶವನ್ನು ಹೊರಡಿಸಿತು. ಈ ಅಕ್ರಮ ಮಂಜೂರಾತಿ ನಡೆಯುವುದನ್ನು ಖಚಿತಪಡಿಸಿಕೊಳ್ಳಲು ರಾಜಕಾರಣಿಯು ಅಧಿಕಾರಿಗಳ ಮೇಲೆ ಒತ್ತಡ ಹೇರಿದ್ದಾರೆ ಮತ್ತು ಬೆದರಿಕೆ ಹಾಕಿದ್ದಾರೆ ಎಂದು ಅವರು ಆರೋಪಿಸಿದ್ದಾರೆ.\n\nಸಾಮಾಜಿಕ ನ್ಯಾಯದ ಕಾಳಜಿ: ವರ್ಷಗಳಿಂದ ಸಣ್ಣ ಭೂಮಿಗಳನ್ನು ಕೃಷಿ ಮಾಡುತ್ತಿರುವ ಬಡ ಜನರಿಗೆ ಅಧಿಕೃತ ಮಂಜೂರಾತಿಯನ್ನು ನಿರಾಕರಿಸಲಾಗುತ್ತಿರುವಾಗ, \"ಮಾಫಿಯಾ\" ಗುಂಪುಗಳಿಗೆ ರಾಜಕೀಯ ಪ್ರಭಾವದ ಮೂಲಕ ದಿನಗಳಲ್ಲಿ ಪ್ರಮುಖ ಸರ್ಕಾರಿ ಭೂಮಿಯನ್ನು ಮಂಜೂರು ಮಾಡಲಾಗುತ್ತಿದೆ ಎಂದು ನಾಯ್ಕ್ ವ್ಯವಸ್ಥೆಯ ದ್ವಂದ್ವತೆಯನ್ನು ಎತ್ತಿ ತೋರಿಸಿದರು.\n\nಕ್ರಿಯಾ ಯೋಜನೆ: ಸಾಗರ್ ರೆಸಿಡೆನ್ಸಿಯಲ್ಲಿ ನಡೆದ ಸಮ್ಮೇಳನದಲ್ಲಿ, ನಾಯ್ಕ್ ಭೂ ಆದೇಶಗಳ ಪ್ರತಿಗಳನ್ನು ಪ್ರದರ್ಶಿಸಿದರು ಮತ್ತು ಈ ಅಕ್ರಮ ಮಂಜೂರಾತಿಯನ್ನು ಪ್ರಶ್ನಿಸಲು ಮತ್ತು ಭೂಮಿಯನ್ನು ಸಾರ್ವಜನಿಕ ಬಳಕೆಗೆ ಹಿಂತಿರುಗಿಸುವುದನ್ನು ಖಚಿತಪಡಿಸಿಕೊಳ್ಳಲು ನ್ಯಾಯಾಲಯವನ್ನು ಸಂಪರ್ಕಿಸುವುದಾಗಿ ಘೋಷಿಸಿದರು.\n\nಪ್ರಮುಖ ಸಾಕ್ಷಿಗಳು: ದಿನೇಶ್ ಮಡಿವಾಳ, ಭಾಸ್ಕರ್ ದೇವಾಡಿಗ, ಯೋಗೇಶ್ ಶೆಟ್ಟಿ ಮತ್ತು ಇತರರು ಸೇರಿದಂತೆ ಹಲವಾರು ಸ್ಥಳೀಯ ವ್ಯಕ್ತಿಗಳು ಪತ್ರಿಕಾಗೋಷ್ಠಿಗೆ ಬೆಂಬಲ ನೀಡಿದರು.",
    category: "Cultural & Community Events"
  },
  {
    id: 9,
    url: "https://raw.githubusercontent.com/townlinksolutions/townlinksolutions/main/masthappna_naik/images/news/news9.jpg",
    titleEn: "Educational Scholarships Distributed",
    titleKn: "ಶೈಕ್ಷಣಿಕ ವಿದ್ಯಾರ್ಥಿವೇತನ ವಿತರಣೆ",
    shortDescEn: "Helping bright students achieve their dreams.",
    shortDescKn: "ಪ್ರತಿಭಾವಂತ ವಿದ್ಯಾರ್ಥಿಗಳು ತಮ್ಮ ಕನಸುಗಳನ್ನು ನನಸಾಗಿಸಲು ಸಹಾಯ ಮಾಡುವುದು.",
    contentEn: "Masthappa Naik distributed scholarships to meritorious students from economically weaker sections, encouraging them to pursue higher education.",
    contentKn: "ಮಾಸ್ತಪ್ಪ ನಾಯ್ಕ ಬಲಸೆ ಅವರು ಆರ್ಥಿಕವಾಗಿ ಹಿಂದುಳಿದ ವರ್ಗಗಳ ಪ್ರತಿಭಾವಂತ ವಿದ್ಯಾರ್ಥಿಗಳಿಗೆ ವಿದ್ಯಾರ್ಥಿವೇತನವನ್ನು ವಿತರಿಸಿದರು, ಉನ್ನತ ಶಿಕ್ಷಣವನ್ನು ಪಡೆಯಲು ಅವರನ್ನು ಪ್ರೋತ್ಸಾಹಿಸಿದರು.",
    category: "Youth Lead"
  },
  {
    id: 10,
    url: "https://raw.githubusercontent.com/townlinksolutions/townlinksolutions/main/masthappna_naik/images/news/news10.jpg",
    titleEn: "Masthappa Naik Raises Concerns Over Irregularities in Land Allocation and Hospital-Related Matters",
    titleKn: "ಭೂ ಹಂಚಿಕೆ ಮತ್ತು ಆಸ್ಪತ್ರೆ ಸಂಬಂಧಿತ ವಿಷಯಗಳಲ್ಲಿನ ಅಕ್ರಮಗಳ ಬಗ್ಗೆ ಮಾಸ್ತಪ್ಪ ನಾಯ್ಕ ಬಲಸೆ ಕಳವಳ",
    shortDescEn: "Masthappa Naik raises concerns over irregularities in land allocation and hospital-related matters, demanding transparency and accountability.",
    shortDescKn: "ಭೂ ಹಂಚಿಕೆ ಮತ್ತು ಆಸ್ಪತ್ರೆ ಸಂಬಂಧಿತ ವಿಷಯಗಳಲ್ಲಿನ ಅಕ್ರಮಗಳ ಬಗ್ಗೆ ಮಾಸ್ತಪ್ಪ ನಾಯ್ಕ ಬಲಸೆ ಕಳವಳ, ಪಾರದರ್ಶಕತೆ ಮತ್ತು ಹೊಣೆಗಾರಿಕೆಗೆ ಆಗ್ರಹ.",
    contentEn: "This news report highlights Masthappa Naik addressing a press conference where he raised serious concerns regarding land allocation and issues connected to hospital development in Bhatkal. He questioned the process followed in allotting land and pointed out possible irregularities affecting public interest.\n\nDuring the interaction, he presented documents and emphasized that decisions related to public resources must be transparent and lawful. He stressed that any misuse or lack of clarity in such matters directly impacts development projects, including essential infrastructure like hospitals.\n\nHe further urged the authorities to investigate the matter thoroughly and take corrective action wherever required. His statements reflected a strong stand for accountability, fairness, and proper governance.\n\nThe presence of supporters and the formal setting of the press meet indicate that the issue has significant public importance. Through such initiatives, Masthappa Naik continues to highlight critical concerns, ensuring that development projects are implemented responsibly and benefit the people.",
    contentKn: "ಈ ಸುದ್ದಿ ವರದಿಯು ಮಾಸ್ತಪ್ಪ ನಾಯ್ಕ ಬಲಸೆ ಅವರು ಪತ್ರಿಕಾಗೋಷ್ಠಿಯನ್ನುದ್ದೇಶಿಸಿ ಮಾತನಾಡುತ್ತಿರುವುದನ್ನು ಎತ್ತಿ ತೋರಿಸುತ್ತದೆ, ಅಲ್ಲಿ ಅವರು ಭಟ್ಕಳದಲ್ಲಿ ಭೂ ಹಂಚಿಕೆ ಮತ್ತು ಆಸ್ಪತ್ರೆ ಅಭಿವೃದ್ಧಿಗೆ ಸಂಬಂಧಿಸಿದ ವಿಷಯಗಳ ಬಗ್ಗೆ ಗಂಭೀರ ಕಳವಳ ವ್ಯಕ್ತಪಡಿಸಿದರು. ಅವರು ಭೂಮಿಯನ್ನು ಹಂಚಿಕೆ ಮಾಡುವಾಗ ಅನುಸರಿಸಿದ ಪ್ರಕ್ರಿಯೆಯನ್ನು ಪ್ರಶ್ನಿಸಿದರು ಮತ್ತು ಸಾರ್ವಜನಿಕ ಹಿತಾಸಕ್ತಿಯ ಮೇಲೆ ಪರಿಣಾಮ ಬೀರುವ ಸಂಭವನೀಯ ಅಕ್ರಮಗಳನ್ನು ಎತ್ತಿ ತೋರಿಸಿದರು.\n\nಸಂವಾದದ ಸಂದರ್ಭದಲ್ಲಿ, ಅವರು ದಾಖಲೆಗಳನ್ನು ಪ್ರಸ್ತುತಪಡಿಸಿದರು ಮತ್ತು ಸಾರ್ವಜನಿಕ ಸಂಪನ್ಮೂಲಗಳಿಗೆ ಸಂಬಂಧಿಸಿದ ನಿರ್ಧಾರಗಳು ಪಾರದರ್ಶಕವಾಗಿ ಮತ್ತು ಕಾನೂನುಬದ್ಧವಾಗಿರಬೇಕು ಎಂದು ಒತ್ತಿ ಹೇಳಿದರು. ಅಂತಹ ವಿಷಯಗಳಲ್ಲಿ ಯಾವುದೇ ದುರುಪಯೋಗ ಅಥವಾ ಸ್ಪಷ್ಟತೆಯ ಕೊರತೆಯು ಆಸ್ಪತ್ರೆಗಳಂತಹ ಅಗತ್ಯ ಮೂಲಸೌಕರ್ಯಗಳನ್ನು ಒಳಗೊಂಡಂತೆ ಅಭಿವೃದ್ಧಿ ಯೋಜನೆಗಳ ಮೇಲೆ ನೇರವಾಗಿ ಪರಿಣಾಮ ಬೀರುತ್ತದೆ ಎಂದು ಅವರು ಒತ್ತಿ ಹೇಳಿದರು.\n\nಅವರು ಅಧಿಕಾರಿಗಳಿಗೆ ಈ ವಿಷಯವನ್ನು ಕೂಲಂಕಷವಾಗಿ ತನಿಖೆ ಮಾಡಲು ಮತ್ತು ಅಗತ್ಯವಿರುವ ಕಡೆಗಳಲ್ಲಿ ಸರಿಪಡಿಸುವ ಕ್ರಮಗಳನ್ನು ತೆಗೆದುಕೊಳ್ಳುವಂತೆ ಮತ್ತಷ್ಟು ಒತ್ತಾಯಿಸಿದರು. ಅವರ ಹೇಳಿಕೆಗಳು ಹೊಣೆಗಾರಿಕೆ, ನ್ಯಾಯಸಮ್ಮತತೆ ಮತ್ತು ಸರಿಯಾದ ಆಡಳಿತಕ್ಕಾಗಿ ಬಲವಾದ ನಿಲುವನ್ನು ಪ್ರತಿಬಿಂಬಿಸುತ್ತವೆ.\n\nಬೆಂಬಲಿಗರ ಉಪಸ್ಥಿತಿ ಮತ್ತು ಪತ್ರಿಕಾಗೋಷ್ಠಿಯ ಔಪಚಾರಿಕ ಸೆಟ್ಟಿಂಗ್ ಈ ವಿಷಯವು ಗಮನಾರ್ಹ ಸಾರ್ವಜನಿಕ ಪ್ರಾಮುಖ್ಯತೆಯನ್ನು ಹೊಂದಿದೆ ಎಂದು ಸೂಚಿಸುತ್ತದೆ. ಇಂತಹ ಉಪಕ್ರಮಗಳ ಮೂಲಕ, ಮಾಸ್ತಪ್ಪ ನಾಯ್ಕ ಬಲಸೆ ಅವರು ನಿರ್ಣಾಯಕ ಕಾಳಜಿಗಳನ್ನು ಎತ್ತಿ ತೋರಿಸುವುದನ್ನು ಮುಂದುವರಿಸಿದ್ದಾರೆ, ಅಭಿವೃದ್ಧಿ ಯೋಜನೆಗಳನ್ನು ಜವಾಬ್ದಾರಿಯುತವಾಗಿ ಜಾರಿಗೆ ತರಲಾಗುತ್ತಿದೆ ಮತ್ತು ಜನರಿಗೆ ಪ್ರಯೋಜನವನ್ನು ನೀಡುತ್ತದೆ ಎಂದು ಖಚಿತಪಡಿಸಿಕೊಳ್ಳುತ್ತಾರೆ.",
    category: "Youth Lead"
  },
  {
    id: 11,
    url: "https://raw.githubusercontent.com/townlinksolutions/townlinksolutions/main/masthappna_naik/images/news/news11.jpg",
    titleEn: "Masthappa Naik Accuses Influential Politician of Illegal Land Grabbing",
    titleKn: "ಪ್ರಭಾವಿ ರಾಜಕಾರಣಿಯಿಂದ ಸರ್ಕಾರಿ ಭೂಮಿ ಕಬಳಿಕೆ: ಮಾಸ್ತಪ್ಪ ನಾಯ್ಕ ಬಲಸೆ ಗಂಭೀರ ಆರೋಪ",
    shortDescEn: "Social activist Masthappa Naik has accused an influential politician of illegally grabbing four acres of high-value government land in Prabhat Nagar, Honnavar, by registering it under \"Benami\" (proxy) names through the Land Tribunal.",
    shortDescKn: "ಸಾಮಾಜಿಕ ಕಾರ್ಯಕರ್ತ ಮಾಸ್ತಪ್ಪ ನಾಯ್ಕ ಬಲಸೆ ಅವರು ಪ್ರಭಾವಿ ರಾಜಕಾರಣಿಯೊಬ್ಬರು ಹೊನ್ನಾವರದ ಪ್ರಭಾತ ನಗರದಲ್ಲಿ ನಾಲ್ಕು ಎಕರೆ ಸರ್ಕಾರಿ ಭೂಮಿಯನ್ನು ಭೂ ನ್ಯಾಯ ಮಂಡಳಿಯ ಮೂಲಕ \"ಬೇನಾಮಿ\" ಹೆಸರಿನಲ್ಲಿ ಅಕ್ರಮವಾಗಿ ಕಬಳಿಸಿದ್ದಾರೆ ಎಂದು ಆರೋಪಿಸಿದ್ದಾರೆ.",
    contentEn: "The Allegation: Masthappa Naik held a press conference at a private hotel in Honnavar, alleging that an influential politician from the Bhatkal-Honnavar constituency misused their power to grab four acres of government land.\n\nThe Land Details: Location: Prabhat Nagar, Honnavar (Survey Numbers 238 and 239). Estimated Value: Approximately ₹50 Crores. History: The land was officially declared as government property twice before, in 1974 and 2004.\n\nModus Operandi: Naik claims that on January 12, 2026, the politician influenced officials to grant the land to four individuals (proxies) via the Land Tribunal. He noted that while poor farmers struggle to get land sanctions for cultivation, influential figures obtain them illegally through corruption.\n\nDemand for Action: Masthappa Naik demanded that the illegal allotment be canceled and the land returned for public use. He also announced his intention to take the matter to court.\n\nAttendees: The press conference was attended by several individuals, including Dinesh Madiwala, Bhaskar Devadiga, Yogesh Shetty, Navin Naik, and others.",
    contentKn: "ಆರೋಪ: ಮಾಸ್ತಪ್ಪ ನಾಯ್ಕ ಬಲಸೆ ಅವರು ಹೊನ್ನಾವರದ ಖಾಸಗಿ ಹೋಟೆಲ್‌ನಲ್ಲಿ ಪತ್ರಿಕಾಗೋಷ್ಠಿಯನ್ನು ನಡೆಸಿ, ಭಟ್ಕಳ-ಹೊನ್ನಾವರ ವಿಧಾನಸಭಾ ಕ್ಷೇತ್ರದ ಪ್ರಭಾವಿ ರಾಜಕಾರಣಿಯೊಬ್ಬರು ತಮ್ಮ ಅಧಿಕಾರವನ್ನು ದುರುಪಯೋಗಪಡಿಸಿಕೊಂಡು ನಾಲ್ಕು ಎಕರೆ ಸರ್ಕಾರಿ ಭೂಮಿಯನ್ನು ಕಬಳಿಸಿದ್ದಾರೆ ಎಂದು ಆರೋಪಿಸಿದರು.\n\nಭೂಮಿಯ ವಿವರಗಳು: ಸ್ಥಳ: ಪ್ರಭಾತ ನಗರ, ಹೊನ್ನಾವರ (ಸರ್ವೆ ನಂಬರ್ 238 ಮತ್ತು 239). ಅಂದಾಜು ಮೌಲ್ಯ: ಸುಮಾರು ₹50 ಕೋಟಿ. ಇತಿಹಾಸ: ಈ ಭೂಮಿಯನ್ನು 1974 ಮತ್ತು 2004 ರಲ್ಲಿ ಎರಡು ಬಾರಿ ಅಧಿಕೃತವಾಗಿ ಸರ್ಕಾರಿ ಆಸ್ತಿ ಎಂದು ಘೋಷಿಸಲಾಗಿತ್ತು.\n\nಕಾರ್ಯವೈಖರಿ: 12 ಜನವರಿ 2026 ರಂದು, ರಾಜಕಾರಣಿಯು ಭೂ ನ್ಯಾಯ ಮಂಡಳಿಯ ಮೂಲಕ ನಾಲ್ಕು ವ್ಯಕ್ತಿಗಳಿಗೆ (ಬೇನಾಮಿ) ಭೂಮಿಯನ್ನು ಮಂಜೂರು ಮಾಡಲು ಅಧಿಕಾರಿಗಳ ಮೇಲೆ ಪ್ರಭಾವ ಬೀರಿದ್ದಾರೆ ಎಂದು ಮಾಸ್ತಪ್ಪ ನಾಯ್ಕ ಬಲಸೆ ಹೇಳಿದ್ದಾರೆ. ಬಡ ರೈತರು ಕೃಷಿಗಾಗಿ ಭೂಮಿ ಮಂಜೂರಾತಿ ಪಡೆಯಲು ಹೆಣಗಾಡುತ್ತಿರುವಾಗ, ಪ್ರಭಾವಿ ವ್ಯಕ್ತಿಗಳು ಭ್ರಷ್ಟಾಚಾರದ ಮೂಲಕ ಅಕ್ರಮವಾಗಿ ಭೂಮಿಯನ್ನು ಪಡೆಯುತ್ತಾರೆ ಎಂದು ಅವರು ಗಮನಸೆಳೆದರು.\n\nಕ್ರಮಕ್ಕೆ ಆಗ್ರಹ: ಅಕ್ರಮ ಮಂಜೂರಾತಿಯನ್ನು ರದ್ದುಗೊಳಿಸಿ, ಭೂಮಿಯನ್ನು ಸಾರ್ವಜನಿಕ ಬಳಕೆಗೆ ಹಿಂತಿರುಗಿಸಬೇಕೆಂದು ಮಾಸ್ತಪ್ಪ ನಾಯ್ಕ ಬಲಸೆ ಒತ್ತಾಯಿಸಿದರು. ಈ ವಿಷಯವನ್ನು ನ್ಯಾಯಾಲಯಕ್ಕೆ ಕೊಂಡೊಯ್ಯುವ ಉದ್ದೇಶವನ್ನೂ ಅವರು ಪ್ರಕಟಿಸಿದರು.\n\nಭಾಗವಹಿಸಿದವರು: ದಿನೇಶ್ ಮಡಿವಾಳ, ಭಾಸ್ಕರ್ ದೇವಾಡಿಗ, ಯೋಗೇಶ್ ಶೆಟ್ಟಿ, ನವೀನ್ ನಾಯ್ಕ್ ಮತ್ತು ಇತರರು ಸೇರಿದಂತೆ ಹಲವರು ಪತ್ರಿಕಾಗೋಷ್ಠಿಯಲ್ಲಿ ಭಾಗವಹಿಸಿದ್ದರು.",
    category: "Administrative Engagement"
  },
  {
    id: 12,
    url: "https://raw.githubusercontent.com/townlinksolutions/townlinksolutions/main/masthappna_naik/images/news/news12.jpg",
    titleEn: "Masthappa Naik Submits Proposal for Government Hospital in Bhatkal",
    titleKn: "ಭಟ್ಕಳದಲ್ಲಿ ಸರ್ಕಾರಿ ಆಸ್ಪತ್ರೆ ಸ್ಥಾಪನೆಗೆ ಮಾಸ್ತಪ್ಪ ನಾಯ್ಕ ಬಲಸೆ ಪ್ರಸ್ತಾವನೆ",
    shortDescEn: "Masthappa Naik submits proposal for establishment of a government hospital in Bhatkal, emphasizing the need for better healthcare access.",
    shortDescKn: "ಭಟ್ಕಳದಲ್ಲಿ ಸರ್ಕಾರಿ ಆಸ್ಪತ್ರೆ ಸ್ಥಾಪನೆಗೆ ಮಾಸ್ತಪ್ಪ ನಾಯ್ಕ ಬಲಸೆ ಪ್ರಸ್ತಾವನೆ, ಉತ್ತಮ ಆರೋಗ್ಯ ಸೇವೆಗಳ ಅಗತ್ಯವನ್ನು ಒತ್ತಿಹೇಳಿದರು.",
    contentEn: "This media report highlights Masthappa Naik’s initiative to improve healthcare infrastructure in Bhatkal by formally submitting a proposal to the government for the establishment of a hospital. The report indicates that he has taken a structured step by presenting official documents and urging authorities to act on the long-standing demand.\n\nThe proposal focuses on addressing the healthcare needs of the region, pointing out the lack of adequate medical facilities and the difficulties faced by residents in accessing timely treatment. By bringing this issue to the attention of higher authorities, he emphasized that healthcare is a critical necessity and should be strengthened at the local level.\n\nThe coverage also reflects that this effort is backed by public concern and is aimed at ensuring better medical services for the community. His proactive approach demonstrates a commitment to long-term development and welfare, especially in essential sectors like health.\n\nThrough this initiative, Masthappa Naik continues to position himself as a leader working towards sustainable solutions and improved quality of life for the people of Bhatkal.",
    contentKn: "ಈ ಮಾಧ್ಯಮ ವರದಿಯು ಭಟ್ಕಳದಲ್ಲಿ ಆಸ್ಪತ್ರೆಯನ್ನು ಸ್ಥಾಪಿಸಲು ಸರ್ಕಾರಕ್ಕೆ ಅಧಿಕೃತವಾಗಿ ಪ್ರಸ್ತಾವನೆಯನ್ನು ಸಲ್ಲಿಸುವ ಮೂಲಕ ಆರೋಗ್ಯ ಮೂಲಸೌಕರ್ಯವನ್ನು ಸುಧಾರಿಸುವ ಮಾಸ್ತಪ್ಪ ನಾಯ್ಕ ಬಲಸೆ ಅವರ ಉಪಕ್ರಮವನ್ನು ಎತ್ತಿ ತೋರಿಸುತ್ತದೆ. ಅವರು ಅಧಿಕೃತ ದಾಖಲೆಗಳನ್ನು ಪ್ರಸ್ತುತಪಡಿಸುವ ಮೂಲಕ ಮತ್ತು ದೀರ್ಘಕಾಲದ ಬೇಡಿಕೆಯ ಮೇಲೆ ಕಾರ್ಯನಿರ್ವಹಿಸುವಂತೆ ಅಧಿಕಾರಿಗಳನ್ನು ಒತ್ತಾಯಿಸುವ ಮೂಲಕ ರಚನಾತ್ಮಕ ಹೆಜ್ಜೆ ಇಟ್ಟಿದ್ದಾರೆ ಎಂದು ವರದಿ ಸೂಚಿಸುತ್ತದೆ.\n\nಈ ಪ್ರಸ್ತಾವನೆಯು ಈ ಪ್ರದೇಶದ ಆರೋಗ್ಯ ಅಗತ್ಯಗಳನ್ನು ಪರಿಹರಿಸುವತ್ತ ಗಮನಹರಿಸುತ್ತದೆ, ಸಾಕಷ್ಟು ವೈದ್ಯಕೀಯ ಸೌಲಭ್ಯಗಳ ಕೊರತೆ ಮತ್ತು ಸಮಯೋಚಿತ ಚಿಕಿತ್ಸೆಯನ್ನು ಪಡೆಯುವಲ್ಲಿ ನಿವಾಸಿಗಳು ಎದುರಿಸುತ್ತಿರುವ ತೊಂದರೆಗಳನ್ನು ಎತ್ತಿ ತೋರಿಸುತ್ತದೆ. ಈ ವಿಷಯವನ್ನು ಉನ್ನತ ಅಧಿಕಾರಿಗಳ ಗಮನಕ್ಕೆ ತರುವ ಮೂಲಕ, ಆರೋಗ್ಯ ರಕ್ಷಣೆಯು ನಿರ್ಣಾಯಕ ಅವಶ್ಯಕತೆಯಾಗಿದೆ ಮತ್ತು ಅದನ್ನು ಸ್ಥಳೀಯ ಮಟ್ಟದಲ್ಲಿ ಬಲಪಡಿಸಬೇಕು ಎಂದು ಅವರು ಒತ್ತಿ ಹೇಳಿದರು.\n\nಈ ಪ್ರಯತ್ನವು ಸಾರ್ವಜನಿಕ ಕಾಳಜಿಯಿಂದ ಬೆಂಬಲಿತವಾಗಿದೆ ಮತ್ತು ಸಮುದಾಯಕ್ಕೆ ಉತ್ತಮ ವೈದ್ಯಕೀಯ ಸೇವೆಗಳನ್ನು ಖಚಿತಪಡಿಸಿಕೊಳ್ಳುವ ಗುರಿಯನ್ನು ಹೊಂದಿದೆ ಎಂದು ವರದಿಯು ಪ್ರತಿಬಿಂಬಿಸುತ್ತದೆ. ಅವರ ಪೂರ್ವಭಾವಿ ವಿಧಾನವು ದೀರ್ಘಕಾಲೀನ ಅಭಿವೃದ್ಧಿ ಮತ್ತು ಕಲ್ಯಾಣಕ್ಕೆ ಬದ್ಧತೆಯನ್ನು ಪ್ರದರ್ಶಿಸುತ್ತದೆ, ವಿಶೇಷವಾಗಿ ಆರೋಗ್ಯದಂತಹ ಅಗತ್ಯ ಕ್ಷೇತ್ರಗಳಲ್ಲಿ.\n\nಈ ಉಪಕ್ರಮದ ಮೂಲಕ, ಮಾಸ್ತಪ್ಪ ನಾಯ್ಕ ಬಲಸೆ ಅವರು ಸುಸ್ಥಿರ ಪರಿಹಾರಗಳು ಮತ್ತು ಭಟ್ಕಳದ ಜನರ ಜೀವನದ ಗುಣಮಟ್ಟವನ್ನು ಸುಧಾರಿಸಲು ಕೆಲಸ ಮಾಡುವ ನಾಯಕರಾಗಿ ತಮ್ಮನ್ನು ತಾವು ಪ್ರತಿಪಾದಿಸುವುದನ್ನು ಮುಂದುವರಿಸಿದ್ದಾರೆ.",
    category: "Organizational Growth"
  },
  {
    id: 13,
    url: "https://raw.githubusercontent.com/townlinksolutions/townlinksolutions/main/masthappna_naik/images/news/news13.jpg",
    titleEn: "Masthappa Naik Raises Concerns Over Healthcare Facilities in Bhatkal",
    titleKn: "ಭಟ್ಕಳದಲ್ಲಿ ಆರೋಗ್ಯ ಸೌಲಭ್ಯಗಳ ಕುರಿತು ಮಾಸ್ತಪ್ಪ ನಾಯ್ಕ ಬಲಸೆ ಕಳವಳ",
    shortDescEn: "Masthappa Naik raises concerns over hospital-related issues in Bhatkal, urging authorities to ensure proper healthcare facilities for the public.",
    shortDescKn: "ಭಟ್ಕಳದಲ್ಲಿ ಆಸ್ಪತ್ರೆಗೆ ಸಂಬಂಧಿಸಿದ ಸಮಸ್ಯೆಗಳ ಬಗ್ಗೆ ಮಾಸ್ತಪ್ಪ ನಾಯ್ಕ ಬಲಸೆ ಕಳವಳ, ಸಾರ್ವಜನಿಕರಿಗೆ ಸೂಕ್ತ ಆರೋಗ್ಯ ಸೌಲಭ್ಯಗಳನ್ನು ಖಚಿತಪಡಿಸಿಕೊಳ್ಳುವಂತೆ ಅಧಿಕಾರಿಗಳಿಗೆ ಒತ್ತಾಯ.",
    contentEn: "This media coverage highlights Masthappa Naik addressing issues related to healthcare facilities in Bhatkal, where concerns were raised about the functioning and management of hospital services. Along with community members, he participated in submitting a formal representation to the authorities regarding these issues.\n\nDuring the interaction, he emphasized the urgent need for improved healthcare infrastructure, proper medical services, and accountability in hospital administration. He stressed that access to quality healthcare is a fundamental necessity and that any shortcomings directly impact the well-being of the public.\n\nThe report also reflects strong public participation, indicating that the issue holds significant importance among local residents. By actively taking up such concerns, Masthappa Naik demonstrates his commitment to addressing critical public needs and ensuring that essential services like healthcare are delivered effectively.\n\nThrough such initiatives, he continues to stand as a responsible leader advocating for better facilities, transparency, and people-centric governance.",
    contentKn: "ಈ ಮಾಧ್ಯಮ ವರದಿಯು ಭಟ್ಕಳದಲ್ಲಿನ ಆರೋಗ್ಯ ಸೌಲಭ್ಯಗಳಿಗೆ ಸಂಬಂಧಿಸಿದ ಸಮಸ್ಯೆಗಳನ್ನು ಮಾಸ್ತಪ್ಪ ನಾಯ್ಕ ಬಲಸೆ ಅವರು ತಿಳಿಸುತ್ತಿರುವುದನ್ನು ಎತ್ತಿ ತೋರಿಸುತ್ತದೆ, ಅಲ್ಲಿ ಆಸ್ಪತ್ರೆ ಸೇವೆಗಳ ಕಾರ್ಯನಿರ್ವಹಣೆ ಮತ್ತು ನಿರ್ವಹಣೆಯ ಬಗ್ಗೆ ಕಳವಳ ವ್ಯಕ್ತಪಡಿಸಲಾಯಿತು. ಸಮುದಾಯದ ಸದಸ್ಯರೊಂದಿಗೆ, ಅವರು ಈ ಸಮಸ್ಯೆಗಳ ಬಗ್ಗೆ ಅಧಿಕಾರಿಗಳಿಗೆ ಔಪಚಾರಿಕ ಮನವಿಯನ್ನು ಸಲ್ಲಿಸುವಲ್ಲಿ ಭಾಗವಹಿಸಿದರು.\n\nಸಂವಾದದ ಸಂದರ್ಭದಲ್ಲಿ, ಅವರು ಸುಧಾರಿತ ಆರೋಗ್ಯ ಮೂಲಸೌಕರ್ಯ, ಸೂಕ್ತ ವೈದ್ಯಕೀಯ ಸೇವೆಗಳು ಮತ್ತು ಆಸ್ಪತ್ರೆ ಆಡಳಿತದಲ್ಲಿ ಹೊಣೆಗಾರಿಕೆಯ ತುರ್ತು ಅಗತ್ಯವನ್ನು ಒತ್ತಿ ಹೇಳಿದರು. ಗುಣಮಟ್ಟದ ಆರೋಗ್ಯ ರಕ್ಷಣೆಯ ಪ್ರವೇಶವು ಮೂಲಭೂತ ಅವಶ್ಯಕತೆಯಾಗಿದೆ ಮತ್ತು ಯಾವುದೇ ನ್ಯೂನತೆಗಳು ನೇರವಾಗಿ ಸಾರ್ವಜನಿಕರ ಯೋಗಕ್ಷೇಮದ ಮೇಲೆ ಪರಿಣಾಮ ಬೀರುತ್ತವೆ ಎಂದು ಅವರು ಒತ್ತಿ ಹೇಳಿದರು.\n\nಈ ವರದಿಯು ಬಲವಾದ ಸಾರ್ವಜನಿಕ ಭಾಗವಹಿಸುವಿಕೆಯನ್ನು ಪ್ರತಿಬಿಂಬಿಸುತ್ತದೆ, ಇದು ಸ್ಥಳೀಯ ನಿವಾಸಿಗಳಲ್ಲಿ ಈ ವಿಷಯವು ಮಹತ್ವದ್ದಾಗಿದೆ ಎಂದು ಸೂಚಿಸುತ್ತದೆ. ಇಂತಹ ಕಾಳಜಿಗಳನ್ನು ಸಕ್ರಿಯವಾಗಿ ತೆಗೆದುಕೊಳ್ಳುವ ಮೂಲಕ, ಮಾಸ್ತಪ್ಪ ನಾಯ್ಕ ಬಲಸೆ ಅವರು ನಿರ್ಣಾಯಕ ಸಾರ್ವಜನಿಕ ಅಗತ್ಯಗಳನ್ನು ಪರಿಹರಿಸಲು ಮತ್ತು ಆರೋಗ್ಯದಂತಹ ಅಗತ್ಯ ಸೇವೆಗಳನ್ನು ಪರಿಣಾಮಕಾರಿಯಾಗಿ ತಲುಪಿಸುವುದನ್ನು ಖಚಿತಪಡಿಸಿಕೊಳ್ಳಲು ತಮ್ಮ ಬದ್ಧತೆಯನ್ನು ಪ್ರದರ್ಶಿಸುತ್ತಾರೆ.\n\nಇಂತಹ ಉಪಕ್ರಮಗಳ ಮೂಲಕ, ಅವರು ಉತ್ತಮ ಸೌಲಭ್ಯಗಳು, ಪಾರದರ್ಶಕತೆ ಮತ್ತು ಜನಕೇಂದ್ರಿತ ಆಡಳಿತಕ್ಕಾಗಿ ಪ್ರತಿಪಾದಿಸುವ ಜವಾಬ್ದಾರಿಯುತ ನಾಯಕರಾಗಿ ನಿಲ್ಲುವುದನ್ನು ಮುಂದುವರಿಸಿದ್ದಾರೆ.",
    category: "Cultural & Community Events"
  },
  {
    id: 14,
    url: "https://raw.githubusercontent.com/townlinksolutions/townlinksolutions/main/masthappna_naik/images/news/news14.jpg",
    titleEn: "Urgent Demand for Specialist Doctors in Bhatkal Hospital",
    titleKn: "ಭಟ್ಕಳ ಆಸ್ಪತ್ರೆಯಲ್ಲಿ ತಜ್ಞ ವೈದ್ಯರ ತುರ್ತು ಬೇಡಿಕೆ",
    shortDescEn: "Masthappa Naik demands immediate recruitment of specialist doctors at the Bhatkal Taluk Government Hospital.",
    shortDescKn: "ಭಟ್ಕಳ ತಾಲೂಕು ಸರ್ಕಾರಿ ಆಸ್ಪತ್ರೆಯಲ್ಲಿ ತಜ್ಞ ವೈದ್ಯರ ನೇಮಕಾತಿಗೆ ಮಾಸ್ತಪ್ಪ ನಾಯ್ಕ ಅವರ ತುರ್ತು ಬೇಡಿಕೆ.",
    contentEn: "Masthappa Naik has raised a strong demand for the immediate recruitment of specialist doctors at the Bhatkal Taluk Government Hospital. He highlighted the severe shortage of medical staff and the resulting hardships faced by the local population. He urged the government to take swift action to ensure quality healthcare services are available to the people of Bhatkal.",
    contentKn: "ಮಾಸ್ತಪ್ಪ ನಾಯ್ಕ ಅವರು ಭಟ್ಕಳ ತಾಲೂಕು ಸರ್ಕಾರಿ ಆಸ್ಪತ್ರೆಯಲ್ಲಿ ತಜ್ಞ ವೈದ್ಯರನ್ನು ತಕ್ಷಣ ನೇಮಕ ಮಾಡಬೇಕೆಂದು ಬಲವಾಗಿ ಒತ್ತಾಯಿಸಿದ್ದಾರೆ. ವೈದ್ಯಕೀಯ ಸಿಬ್ಬಂದಿಯ ತೀವ್ರ ಕೊರತೆ ಮತ್ತು ಇದರಿಂದ ಸ್ಥಳೀಯ ಜನತೆ ಎದುರಿಸುತ್ತಿರುವ ತೊಂದರೆಗಳನ್ನು ಅವರು ಎತ್ತಿ ತೋರಿಸಿದರು. ಭಟ್ಕಳದ ಜನರಿಗೆ ಗುಣಮಟ್ಟದ ಆರೋಗ್ಯ ಸೇವೆಗಳು ಲಭ್ಯವಾಗುವಂತೆ ಸರ್ಕಾರವು ತ್ವರಿತ ಕ್ರಮ ಕೈಗೊಳ್ಳಬೇಕೆಂದು ಅವರು ಆಗ್ರಹಿಸಿದರು.",
    category: "Administrative Engagement"
  },
  {
    id: 15,
    url: "https://raw.githubusercontent.com/townlinksolutions/townlinksolutions/main/masthappna_naik/images/news/news15.jpg",
    titleEn: "Legal Action Against Illegal Land Sanction in Honnavar",
    titleKn: "ಹೊನ್ನಾವರದಲ್ಲಿ ಅಕ್ರಮ ಭೂ ಮಂಜೂರಾತಿ ವಿರುದ್ಧ ಕಾನೂನು ಕ್ರಮ",
    shortDescEn: "Masthappa Naik decides to move court against the illegal 'Benami' sanction of government land in Honnavar.",
    shortDescKn: "ಹೊನ್ನಾವರದಲ್ಲಿ ಸರ್ಕಾರಿ ಭೂಮಿಯ ಅಕ್ರಮ 'ಬಿನಾಮಿ' ಮಂಜೂರಾತಿ ವಿರುದ್ಧ ನ್ಯಾಯಾಲಯದ ಮೊರೆಹೋಗಲು ಮಾಸ್ತಪ್ಪ ನಾಯ್ಕ ನಿರ್ಧಾರ.",
    contentEn: "Masthappa Naik has decided to take legal action against the illegal 'Benami' sanction of government land in Honnavar. He alleged that valuable government land has been misappropriated through fraudulent means and vowed to fight for its recovery. He emphasized that he will not tolerate such illegal activities and will pursue the matter in court to ensure justice is served.",
    contentKn: "ಹೊನ್ನಾವರದಲ್ಲಿ ಸರ್ಕಾರಿ ಭೂಮಿಯ ಅಕ್ರಮ 'ಬಿನಾಮಿ' ಮಂಜೂರಾತಿ ವಿರುದ್ಧ ಕಾನೂನು ಕ್ರಮ ಕೈಗೊಳ್ಳಲು ಮಾಸ್ತಪ್ಪ ನಾಯ್ಕ ನಿರ್ಧರಿಸಿದ್ದಾರೆ. ಅಮೂಲ್ಯವಾದ ಸರ್ಕಾರಿ ಭೂಮಿಯನ್ನು ಮೋಸದ ಮಾರ್ಗಗಳ ಮೂಲಕ ದುರುಪಯೋಗಪಡಿಸಿಕೊಳ್ಳಲಾಗಿದೆ ಎಂದು ಅವರು ಆರೋಪಿಸಿದ್ದಾರೆ ಮತ್ತು ಅದನ್ನು ಮರಳಿ ಪಡೆಯಲು ಹೋರಾಡುವುದಾಗಿ ಪ್ರತಿಜ್ಞೆ ಮಾಡಿದ್ದಾರೆ. ಇಂತಹ ಅಕ್ರಮ ಚಟುವಟಿಕೆಗಳನ್ನು ತಾನು ಸಹಿಸುವುದಿಲ್ಲ ಮತ್ತು ನ್ಯಾಯ ಸಿಗುವಂತೆ ಮಾಡಲು ನ್ಯಾಯಾಲಯದಲ್ಲಿ ಈ ವಿಷಯವನ್ನು ಮುಂದುವರಿಸುವುದಾಗಿ ಅವರು ಒತ್ತಿ ಹೇಳಿದರು.",
    category: "Justice & Anti-Corruption Stand"
  },
  {
    id: 16,
    url: "https://raw.githubusercontent.com/townlinksolutions/townlinksolutions/main/masthappna_naik/images/news/news16.jpg",
    titleEn: "Appeal to Police Against Ganja Sale and Cattle Theft in Bhatkal/Murdeshwar",
    titleKn: "ಭಟ್ಕಳ/ಮೂರ್ಡೇಶ್ವರದಲ್ಲಿ ಗಾಂಜಾ ಮಾರಾಟ ಮತ್ತು ಜಾನುವಾರು ಕಳ್ಳತನದ ವಿರುದ್ಧ ಪೊಲೀಸರಿಗೆ ಮನವಿ",
    shortDescEn: "Masthappa Naik appeals to police for stringent action against illegal Ganja sale and cattle theft in Bhatkal and Murdeshwar.",
    shortDescKn: "ಭಟ್ಕಳ ಮತ್ತು ಮೂರ್ಡೇಶ್ವರದಲ್ಲಿ ಅಕ್ರಮ ಗಾಂಜಾ ಮಾರಾಟ ಮತ್ತು ಜಾನುವಾರು ಕಳ್ಳತನದ ವಿರುದ್ಧ ಕಠಿಣ ಕ್ರಮ ಕೈಗೊಳ್ಳುವಂತೆ ಮಾಸ್ತಪ್ಪ ನಾಯ್ಕ ಪೊಲೀಸರಿಗೆ ಮನವಿ.",
    contentEn: "Masthappa Naik has appealed to the police authorities to take stringent action against the rising incidents of illegal Ganja sale and cattle theft in Bhatkal and Murdeshwar. He expressed concern over the impact of these criminal activities on the safety and security of the local community. He urged the police to increase patrolling and take decisive steps to curb these illegal operations.",
    contentKn: "ಭಟ್ಕಳ ಮತ್ತು ಮೂರ್ಡೇಶ್ವರದಲ್ಲಿ ಹೆಚ್ಚುತ್ತಿರುವ ಅಕ್ರಮ ಗಾಂಜಾ ಮಾರಾಟ ಮತ್ತು ಜಾನುವಾರು ಕಳ್ಳತನದ ವಿರುದ್ಧ ಕಠಿಣ ಕ್ರಮ ಕೈಗೊಳ್ಳುವಂತೆ ಮಾಸ್ತಪ್ಪ ನಾಯ್ಕ ಅವರು ಪೊಲೀಸ್ ಅಧಿಕಾರಿಗಳಿಗೆ ಮನವಿ ಮಾಡಿದ್ದಾರೆ. ಈ ಕ್ರಿಮಿನಲ್ ಚಟುವಟಿಕೆಗಳು ಸ್ಥಳೀಯ ಸಮುದಾಯದ ಸುರಕ್ಷತೆ ಮತ್ತು ಭದ್ರತೆಯ ಮೇಲೆ ಬೀರುತ್ತಿರುವ ಪರಿಣಾಮದ ಬಗ್ಗೆ ಅವರು ಕಳವಳ ವ್ಯಕ್ತಪಡಿಸಿದ್ದಾರೆ. ಗಸ್ತು ಹೆಚ್ಚಿಸಲು ಮತ್ತು ಈ ಅಕ್ರಮ ಕಾರ್ಯಾಚರಣೆಗಳನ್ನು ತಡೆಯಲು ನಿರ್ಣಾಯಕ ಕ್ರಮಗಳನ್ನು ತೆಗೆದುಕೊಳ್ಳುವಂತೆ ಅವರು ಪೊಲೀಸರನ್ನು ಒತ್ತಾಯಿಸಿದ್ದಾರೆ.",
    category: "Justice & Anti-Corruption Stand"
  },
  {
    id: 17,
    url: "https://raw.githubusercontent.com/townlinksolutions/townlinksolutions/main/masthappna_naik/images/news/news17.jpg",
    titleEn: "Political Turmoil at Sharavati Project Opposition Meeting",
    titleKn: "ಶರಾವತಿ ಯೋಜನೆ ವಿರೋಧಿ ಸಭೆಯಲ್ಲಿ ರಾಜಕೀಯ ಗದ್ದಲ",
    shortDescEn: "A report on the dramatic political clash at the Sharavati Project opposition meeting in Honnavar, where Masthappa Naik and Minister Mankal Vaidya engaged in a sharp exchange of words on stage in front of religious leaders.",
    shortDescKn: "ಹೊನ್ನಾವರದಲ್ಲಿ ನಡೆದ ಶರಾವತಿ ಯೋಜನೆ ವಿರೋಧಿ ಸಭೆಯಲ್ಲಿ ಮಾಸ್ತಪ್ಪ ನಾಯಕ್ ಮತ್ತು ಸಚಿವ ಮಂಕಾಳ ವೈದ್ಯ ಅವರ ನಡುವೆ ಧಾರ್ಮಿಕ ಮುಖಂಡರ ಸಮ್ಮುಖದಲ್ಲಿ ವೇದಿಕೆಯ ಮೇಲೆ ನಡೆದ ತೀವ್ರ ವಾಗ್ವಾದದ ವರದಿ.",
    contentEn: "The news article captures a tense moment at the Munda Ganapati Sabhabhavana, where a gathering intended to unite against the Sharavati Pumped Storage Project turned into a platform for political rivalry and public apologies.\n\nKey Highlights:\nThe Confrontation: The headline—\"Political Turmoil at Sharavati Project Opposition Meeting\"—refers to the verbal spat between Minister Mankal Vaidya and social activist Masthappa Naik Balle. The argument broke out on the dais in the presence of several Swamijis (religious leaders).\nMasthappa Naik's Allegations: Masthappa Naik criticized the government’s lack of transparency and accused the district's in-charge minister of not taking a firm stand to stop the project despite having the power to do so. He highlighted that the Padayatra from Gerusoppa to Honnavar was a people's movement that shouldn't be dismissed as a political stunt.\nThe Minister's Retort: Minister Mankal Vaidya reacted strongly, calling the accusations baseless and accusing Masthappa of engaging in \"double-dealing\" politics and using social media to spread misinformation. He challenged the critics to stop playing politics with a serious environmental issue.\nA Rare Apology: In a significant turn of events, former MLA Sunil Naik publicly apologized on stage. He admitted that the initial approval for the project happened during the previous government's tenure while he was in power, stating, \"It was a mistake on my part, and I seek your forgiveness.\" He urged the current minister to use his influence to cancel the project now.\nThe Religious Context: The presence of various Swamijis added weight to the event. They expressed that the Sharavati River is a lifeline for the district and should not be destroyed for power projects, regardless of which political party is in charge.\nPublic Sentiment: The report underscores the growing frustration among the people of Uttara Kannada, who feel caught between political infighting while their natural resources are at stake.",
    contentKn: "ಮುಂಡಾ ಗಣಪತಿ ಸಭಾಭವನದಲ್ಲಿ ನಡೆದ ಶರಾವತಿ ಪಂಪ್ಡ್ ಸ್ಟೋರೇಜ್ ಯೋಜನೆ ವಿರೋಧಿ ಸಭೆಯು ರಾಜಕೀಯ ಪೈಪೋಟಿ ಮತ್ತು ಸಾರ್ವಜನಿಕ ಕ್ಷಮೆಯಾಚನೆಯ ವೇದಿಕೆಯಾಗಿ ಮಾರ್ಪಟ್ಟ ಉದ್ವಿಗ್ನ ಕ್ಷಣವನ್ನು ಈ ಸುದ್ದಿ ಲೇಖನ ಸೆರೆಹಿಡಿದಿದೆ. <br><br><strong>ಪ್ರಮುಖ ಅಂಶಗಳು:</strong><br> ಮುಖಾಮುಖಿ: \"ಶರಾವತಿ ಯೋಜನೆ ವಿರೋಧಿ ಸಭೆಯಲ್ಲಿ ರಾಜಕೀಯ ಗದ್ದಲ\" ಎಂಬ ತಲೆಬರಹವು ಸಚಿವ ಮಂಕಾಳ ವೈದ್ಯ ಮತ್ತು ಸಾಮಾಜಿಕ ಕಾರ್ಯಕರ್ತ ಮಾಸ್ತಪ್ಪ ನಾಯ್ಕ ಬಲಸೆ ಬಳ್ಳೆ ನಡುವಿನ ವಾಗ್ವಾದವನ್ನು ಉಲ್ಲೇಖಿಸುತ್ತದೆ. ಹಲವಾರು ಸ್ವಾಮೀಜಿಗಳ (ಧಾರ್ಮಿಕ ಮುಖಂಡರ) ಸಮ್ಮುಖದಲ್ಲಿ ವೇದಿಕೆಯ ಮೇಲೆ ಈ ವಾಗ್ವಾದ ನಡೆಯಿತು. ಮಾಸ್ತಪ್ಪ ನಾಯ್ಕ ಬಲಸೆ ಅವರ ಆರೋಪಗಳು: ಸರ್ಕಾರದ ಪಾರದರ್ಶಕತೆಯ ಕೊರತೆಯನ್ನು ಟೀಕಿಸಿದ ಮಾಸ್ತಪ್ಪ ನಾಯ್ಕ ಬಲಸೆ, ಯೋಜನೆಯನ್ನು ನಿಲ್ಲಿಸುವ ಅಧಿಕಾರವಿದ್ದರೂ ಜಿಲ್ಲಾ ಉಸ್ತುವಾರಿ ಸಚಿವರು ದೃಢವಾದ ನಿಲುವು ತೆಗೆದುಕೊಳ್ಳುತ್ತಿಲ್ಲ ಎಂದು ಆರೋಪಿಸಿದರು. ಗೇರುಸೊಪ್ಪಾದಿಂದ ಹೊನ್ನಾವರದವರೆಗಿನ ಪಾದಯಾತ್ರೆಯು ಜನರ ಚಳುವಳಿಯಾಗಿದ್ದು, ಅದನ್ನು ರಾಜಕೀಯ ಗಿಮಿಕ್ ಎಂದು ತಳ್ಳಿಹಾಕಬಾರದು ಎಂದು ಅವರು ಒತ್ತಿ ಹೇಳಿದರು. ಸಚಿವರ ತಿರುಗೇಟು: ಸಚಿವ ಮಂಕಾಳ ವೈದ್ಯ ತೀವ್ರವಾಗಿ ಪ್ರತಿಕ್ರಿಯಿಸಿ, ಆರೋಪಗಳನ್ನು ಆಧಾರರಹಿತ ಎಂದು ಕರೆದರು ಮತ್ತು ಮಾಸ್ತಪ್ಪ ಅವರು \"ದ್ವಂದ್ವ\" ರಾಜಕೀಯದಲ್ಲಿ ತೊಡಗಿದ್ದಾರೆ ಮತ್ತು ತಪ್ಪು ಮಾಹಿತಿಯನ್ನು ಹರಡಲು ಸಾಮಾಜಿಕ ಜಾಲತಾಣಗಳನ್ನು ಬಳಸುತ್ತಿದ್ದಾರೆ ಎಂದು ಆರೋಪಿಸಿದರು. ಗಂಭೀರ ಪರಿಸರ ಸಮಸ್ಯೆಯೊಂದಿಗೆ ರಾಜಕೀಯ ಮಾಡುವುದನ್ನು ನಿಲ್ಲಿಸುವಂತೆ ಅವರು ಟೀಕಾಕಾರರಿಗೆ ಸವಾಲು ಹಾಕಿದರು. ಅಪರೂಪದ ಕ್ಷಮೆಯಾಚನೆ: ಒಂದು ಮಹತ್ವದ ಬೆಳವಣಿಗೆಯಲ್ಲಿ, ಮಾಜಿ ಶಾಸಕ ಸುನಿಲ್ ನಾಯಕ್ ವೇದಿಕೆಯ ಮೇಲೆ ಸಾರ್ವಜನಿಕವಾಗಿ ಕ್ಷಮೆಯಾಚಿಸಿದರು. ಹಿಂದಿನ ಸರ್ಕಾರದ ಅವಧಿಯಲ್ಲಿ ತಾವು ಅಧಿಕಾರದಲ್ಲಿದ್ದಾಗ ಯೋಜನೆಗೆ ಆರಂಭಿಕ ಅನುಮೋದನೆ ನೀಡಲಾಗಿತ್ತು ಎಂಬುದನ್ನು ಒಪ್ಪಿಕೊಂಡ ಅವರು, \"ಇದು ನನ್ನ ಕಡೆಯಿಂದಾದ ತಪ್ಪು, ಮತ್ತು ನಾನು ನಿಮ್ಮ ಕ್ಷಮೆಯಾಚಿಸುತ್ತೇನೆ\" ಎಂದು ಹೇಳಿದರು. ಈಗ ಯೋಜನೆಯನ್ನು ರದ್ದುಗೊಳಿಸಲು ಪ್ರಸ್ತುತ ಸಚಿವರು ತಮ್ಮ ಪ್ರಭಾವವನ್ನು ಬಳಸಬೇಕೆಂದು ಅವರು ಒತ್ತಾಯಿಸಿದರು. ಧಾರ್ಮಿಕ ಹಿನ್ನೆಲೆ: ವಿವಿಧ ಸ್ವಾಮೀಜಿಗಳ ಉಪಸ್ಥಿತಿಯು ಕಾರ್ಯಕ್ರಮಕ್ಕೆ ತೂಕವನ್ನು ನೀಡಿತು. ಶರಾವತಿ ನದಿಯು ಜಿಲ್ಲೆಯ ಜೀವನಾಡಿಯಾಗಿದ್ದು, ಯಾವ ರಾಜಕೀಯ ಪಕ್ಷ ಅಧಿಕಾರದಲ್ಲಿದ್ದರೂ ವಿದ್ಯುತ್ ಯೋಜನೆಗಳಿಗಾಗಿ ಅದನ್ನು ನಾಶಪಡಿಸಬಾರದು ಎಂದು ಅವರು ವ್ಯಕ್ತಪಡಿಸಿದರು. ಸಾರ್ವಜನಿಕ ಭಾವನೆ: ತಮ್ಮ ನೈಸರ್ಗಿಕ ಸಂಪನ್ಮೂಲಗಳು ಅಪಾಯದಲ್ಲಿರುವಾಗ ರಾಜಕೀಯ ಒಳಜಗಳಗಳ ನಡುವೆ ಸಿಲುಕಿಕೊಂಡಿರುವ ಉತ್ತರ ಕನ್ನಡದ ಜನರ ಹೆಚ್ಚುತ್ತಿರುವ ಹತಾಶೆಯನ್ನು ಈ ವರದಿ ಒತ್ತಿಹೇಳುತ್ತದೆ.",
    category: "Sharavathi Project & Environmental Movement"
  },
  {
    id: 18,
    url: "https://raw.githubusercontent.com/townlinksolutions/townlinksolutions/main/masthappna_naik/images/news/news18.jpg",
    titleEn: "Allegations and Counter-Allegations on the Public Convention Stage",
    titleKn: "ಸಾರ್ವಜನಿಕ ಸಮಾವೇಶದ ವೇದಿಕೆಯಲ್ಲಿ ಆರೋಪ-ಪ್ರತ್ಯಾರೋಪಗಳು",
    shortDescEn: "A report on the massive public convention (Janasamavesha) in Honnavar where leaders across party lines gathered to oppose the Sharavati Pumped Storage Project, marked by a high-voltage exchange of allegations on stage.",
    shortDescKn: "ಹೊನ್ನಾವರದಲ್ಲಿ ನಡೆದ ಬೃಹತ್ ಸಾರ್ವಜನಿಕ ಸಮಾವೇಶದ (ಜನಸಮಾವೇಶ) ವರದಿ, ಅಲ್ಲಿ ಶರಾವತಿ ಪಂಪ್ಡ್ ಸ್ಟೋರೇಜ್ ಯೋಜನೆಯನ್ನು ವಿರೋಧಿಸಲು ಪಕ್ಷಾತೀತವಾಗಿ ನಾಯಕರು ಸೇರಿದ್ದರು, ಇದು ವೇದಿಕೆಯ ಮೇಲಿನ ತೀವ್ರ ಆರೋಪ-ಪ್ರತ್ಯಾರೋಪಗಳಿಂದ ಗುರುತಿಸಲ್ಪಟ್ಟಿದೆ.",
    contentEn: "The article covers the \"Sharavati Ulisi Horata Samiti\" meeting held at the Munda Ganapati Sabhabhavana. It highlights how the environmental cause brought together diverse political figures, though not without significant friction. <br><br><strong>Key Highlights:</strong><br> <strong>Allegations and Counter-Allegations:</strong> The headline—\"Allegations and Counter-Allegations on the Public Convention Stage\"—captures the heated debate between District In-charge Minister Mankal Vaidya and social activist Masthappa Naik Balle. <strong>The Project's History:</strong> The report clarifies that the Sharavati Pumped Storage Project was not a recent creation but had roots going back to 2017-18. It mentions that 2,410 acres of forest land were initially identified for the project, a point of contention used by various leaders to shift responsibility. Masthappa Naik’s <strong>Bold Stance:</strong> Masthappa Naik questioned why the current administration hasn't taken a definitive step to cancel the project if they truly oppose it. He emphasized that the people's Padayatra was a genuine cry for help, not a stage for political games. Minister’s <strong>Defense:</strong> Minister Mankal Vaidya stated that the project was a legacy of the previous government. He accused critics of trying to \"blackmail\" or gain political mileage through social media rather than understanding the administrative complexities. <strong>United Opposition:</strong> Despite the verbal clashes, the convention successfully brought together former MLA Sunil Naik, various Swamijis, and environmentalists. They collectively passed a resolution that the project must be scrapped to prevent the destruction of Uttara Kannada's ecosystem. The \"Commission\" <strong>Allegation:</strong> Some speakers touched upon the concern that such mega-projects are often driven by \"commissions\" rather than public necessity, a sentiment that resonated strongly with the large crowd in attendance.",
    contentKn: "ಮುಂಡಾ ಗಣಪತಿ ಸಭಾಭವನದಲ್ಲಿ ನಡೆದ \"ಶರಾವತಿ ಉಳಿಸಿ ಹೋರಾಟ ಸಮಿತಿ\" ಸಭೆಯನ್ನು ಲೇಖನವು ಒಳಗೊಂಡಿದೆ. ಪರಿಸರ ಕಾಳಜಿಯು ವಿವಿಧ ರಾಜಕೀಯ ವ್ಯಕ್ತಿಗಳನ್ನು ಹೇಗೆ ಒಟ್ಟುಗೂಡಿಸಿತು ಎಂಬುದನ್ನು ಇದು ಎತ್ತಿ ತೋರಿಸುತ್ತದೆ, ಆದರೂ ಗಮನಾರ್ಹ ಘರ್ಷಣೆಯಿಲ್ಲದೆ ಅಲ್ಲ. <br><br><strong>ಪ್ರಮುಖ ಅಂಶಗಳು:</strong><br> ಆರೋಪಗಳು ಮತ್ತು ಪ್ರತ್ಯಾರೋಪಗಳು: \"ಸಾರ್ವಜನಿಕ ಸಮಾವೇಶದ ವೇದಿಕೆಯಲ್ಲಿ ಆರೋಪ-ಪ್ರತ್ಯಾರೋಪಗಳು\" ಎಂಬ ತಲೆಬರಹವು ಜಿಲ್ಲಾ ಉಸ್ತುವಾರಿ ಸಚಿವ ಮಂಕಾಳ ವೈದ್ಯ ಮತ್ತು ಸಾಮಾಜಿಕ ಕಾರ್ಯಕರ್ತ ಮಾಸ್ತಪ್ಪ ನಾಯ್ಕ ಬಲಸೆ ಬಳ್ಳೆ ನಡುವಿನ ಬಿಸಿಯಾದ ಚರ್ಚೆಯನ್ನು ಸೆರೆಹಿಡಿಯುತ್ತದೆ. ಯೋಜನೆಯ ಇತಿಹಾಸ: ಶರಾವತಿ ಪಂಪ್ಡ್ ಸ್ಟೋರೇಜ್ ಯೋಜನೆಯು ಇತ್ತೀಚಿನ ಸೃಷ್ಟಿಯಲ್ಲ ಆದರೆ 2017-18 ರ ಹಿಂದಿನ ಬೇರುಗಳನ್ನು ಹೊಂದಿದೆ ಎಂದು ವರದಿ ಸ್ಪಷ್ಟಪಡಿಸುತ್ತದೆ. ಯೋಜನೆಗಾಗಿ ಆರಂಭದಲ್ಲಿ 2,410 ಎಕರೆ ಅರಣ್ಯ ಭೂಮಿಯನ್ನು ಗುರುತಿಸಲಾಗಿತ್ತು ಎಂದು ಅದು ಉಲ್ಲೇಖಿಸುತ್ತದೆ, ಇದು ಜವಾಬ್ದಾರಿಯನ್ನು ವರ್ಗಾಯಿಸಲು ವಿವಿಧ ನಾಯಕರು ಬಳಸುವ ವಿವಾದದ ಅಂಶವಾಗಿದೆ. ಮಾಸ್ತಪ್ಪ ನಾಯಕ್ ಅವರ ದಿಟ್ಟ ನಿಲುವು: ಪ್ರಸ್ತುತ ಆಡಳಿತವು ಯೋಜನೆಯನ್ನು ನಿಜವಾಗಿಯೂ ವಿರೋಧಿಸುತ್ತಿದ್ದರೆ ಅದನ್ನು ರದ್ದುಗೊಳಿಸಲು ನಿರ್ಣಾಯಕ ಹೆಜ್ಜೆಯನ್ನು ಏಕೆ ತೆಗೆದುಕೊಂಡಿಲ್ಲ ಎಂದು ಮಾಸ್ತಪ್ಪ ನಾಯಕ್ ಪ್ರಶ್ನಿಸಿದರು. ಜನರ ಪಾದಯಾತ್ರೆಯು ಸಹಾಯಕ್ಕಾಗಿ ನಿಜವಾದ ಕೂಗು, ರಾಜಕೀಯ ಆಟಗಳಿಗೆ ವೇದಿಕೆಯಲ್ಲ ಎಂದು ಅವರು ಒತ್ತಿ ಹೇಳಿದರು. ಸಚಿವರ ಸಮರ್ಥನೆ: ಈ ಯೋಜನೆಯು ಹಿಂದಿನ ಸರ್ಕಾರದ ಕೊಡುಗೆ ಎಂದು ಸಚಿವ ಮಂಕಾಳ ವೈದ್ಯ ಹೇಳಿದ್ದಾರೆ. ಆಡಳಿತಾತ್ಮಕ ಸಂಕೀರ್ಣತೆಗಳನ್ನು ಅರ್ಥಮಾಡಿಕೊಳ್ಳುವ ಬದಲು ಸಾಮಾಜಿಕ ಮಾಧ್ಯಮಗಳ ಮೂಲಕ \"ಬ್ಲ್ಯಾಕ್‌ಮೇಲ್\" ಮಾಡಲು ಅಥವಾ ರಾಜಕೀಯ ಲಾಭ ಪಡೆಯಲು ಟೀಕಾಕಾರರು ಪ್ರಯತ್ನಿಸುತ್ತಿದ್ದಾರೆ ಎಂದು ಅವರು ಆರೋಪಿಸಿದರು. ಯುನೈಟೆಡ್ ವಿರೋಧ: ಮೌಖಿಕ ಘರ್ಷಣೆಗಳ ಹೊರತಾಗಿಯೂ, ಸಮಾವೇಶವು ಮಾಜಿ ಶಾಸಕ ಸುನಿಲ್ ನಾಯಕ್, ವಿವಿಧ ಸ್ವಾಮೀಜಿಗಳು ಮತ್ತು ಪರಿಸರವಾದಿಗಳನ್ನು ಯಶಸ್ವಿಯಾಗಿ ಒಟ್ಟುಗೂಡಿಸಿತು. ಉತ್ತರ ಕನ್ನಡದ ಪರಿಸರ ವ್ಯವಸ್ಥೆಯ ನಾಶವನ್ನು ತಡೆಗಟ್ಟಲು ಯೋಜನೆಯನ್ನು ರದ್ದುಗೊಳಿಸಬೇಕು ಎಂದು ಅವರು ಒಟ್ಟಾಗಿ ನಿರ್ಣಯವನ್ನು ಅಂಗೀಕರಿಸಿದರು. \"ಕಮಿಷನ್\" ಆರೋಪ: ಅಂತಹ ಮೆಗಾ-ಯೋಜನೆಗಳು ಸಾರ್ವಜನಿಕ ಅಗತ್ಯಕ್ಕಿಂತ ಹೆಚ್ಚಾಗಿ \"ಕಮಿಷನ್\" ಗಳಿಂದ ನಡೆಸಲ್ಪಡುತ್ತವೆ ಎಂಬ ಕಳವಳವನ್ನು ಕೆಲವು ಭಾಷಣಕಾರರು ಸ್ಪರ್ಶಿಸಿದರು, ಇದು ಹಾಜರಿದ್ದ ದೊಡ್ಡ ಜನಸಂದಣಿಯೊಂದಿಗೆ ಬಲವಾಗಿ ಪ್ರತಿಧ್ವನಿಸಿತು.",
    category: "Sharavathi Project & Environmental Movement"
  },
  {
    id: 19,
    url: "https://raw.githubusercontent.com/townlinksolutions/townlinksolutions/main/masthappna_naik/images/news/news19.jpg",
    titleEn: "Prioritize Environment Over Political Blame Games",
    titleKn: "ರಾಜಕೀಯ ದೂಷಣೆಗಳಿಗಿಂತ ಪರಿಸರಕ್ಕೆ ಆದ್ಯತೆ ನೀಡಿ",
    shortDescEn: "Masthappa Naik highlights public issues and urges authorities to take swift, responsible action for the welfare of citizens.",
    shortDescKn: "ಮಾಸ್ತಪ್ಪ ನಾಯ್ಕ ಬಲಸೆ ಅವರು ಸಾರ್ವಜನಿಕ ಸಮಸ್ಯೆಗಳನ್ನು ಎತ್ತಿ ತೋರಿಸುತ್ತಾರೆ ಮತ್ತು ನಾಗರಿಕರ ಕಲ್ಯಾಣಕ್ಕಾಗಿ ಅಧಿಕಾರಿಗಳು ತ್ವರಿತ, ಜವಾಬ್ದಾರಿಯುತ ಕ್ರಮ ಕೈಗೊಳ್ಳುವಂತೆ ಒತ್ತಾಯಿಸುತ್ತಾರೆ.",
    contentEn: "As featured in this media report, Masthappa Naik addressed key concerns affecting the public and emphasized the urgent need for administrative action. He pointed out challenges faced by citizens at the grassroots level and called on responsible authorities to respond with efficiency and accountability.\n\nDuring his statement, he stressed the importance of transparent governance, proper implementation of policies, and timely resolution of issues impacting daily life. His approach reflects a commitment to ensuring that governance remains people-centric and responsive.\n\nThe report also showcases his growing influence and public connect, with increasing support from local communities and leaders. Through consistent engagement and advocacy, Masthappa Naik continues to reinforce his role as a dedicated leader focused on development, justice, and the well-being of society.",
    contentKn: "ಈ ಮಾಧ್ಯಮ ವರದಿಯಲ್ಲಿ ತೋರಿಸಿರುವಂತೆ, ಮಾಸ್ತಪ್ಪ ನಾಯ್ಕ ಬಲಸೆ ಅವರು ಸಾರ್ವಜನಿಕರನ್ನು ಬಾಧಿಸುವ ಪ್ರಮುಖ ಕಾಳಜಿಗಳನ್ನು ತಿಳಿಸಿದರು ಮತ್ತು ಆಡಳಿತಾತ್ಮಕ ಕ್ರಮದ ತುರ್ತು ಅಗತ್ಯವನ್ನು ಒತ್ತಿ ಹೇಳಿದರು. ಅವರು ತಳಮಟ್ಟದಲ್ಲಿ ನಾಗರಿಕರು ಎದುರಿಸುತ್ತಿರುವ ಸವಾಲುಗಳನ್ನು ಎತ್ತಿ ತೋರಿಸಿದರು ಮತ್ತು ಜವಾಬ್ದಾರಿಯುತ ಅಧಿಕಾರಿಗಳು ದಕ್ಷತೆ ಮತ್ತು ಹೊಣೆಗಾರಿಕೆಯೊಂದಿಗೆ ಸ್ಪಂದಿಸುವಂತೆ ಕರೆ ನೀಡಿದರು.\n\nತಮ್ಮ ಹೇಳಿಕೆಯ ಸಂದರ್ಭದಲ್ಲಿ, ಅವರು ಪಾರದರ್ಶಕ ಆಡಳಿತ, ನೀತಿಗಳ ಸರಿಯಾದ ಅನುಷ್ಠಾನ ಮತ್ತು ದೈನಂದಿನ ಜೀವನದ ಮೇಲೆ ಪರಿಣಾಮ ಬೀರುವ ಸಮಸ್ಯೆಗಳ ಸಮಯೋಚಿತ ಪರಿಹಾರದ ಮಹತ್ವವನ್ನು ಒತ್ತಿ ಹೇಳಿದರು. ಅವರ ವಿಧಾನವು ಆಡಳಿತವು ಜನಕೇಂದ್ರಿತವಾಗಿ ಮತ್ತು ಸ್ಪಂದಿಸುವಂತೆ ನೋಡಿಕೊಳ್ಳುವ ಬದ್ಧತೆಯನ್ನು ಪ್ರತಿಬಿಂಬಿಸುತ್ತದೆ.\n\nಈ ವರದಿಯು ಅವರ ಬೆಳೆಯುತ್ತಿರುವ ಪ್ರಭಾವ ಮತ್ತು ಸಾರ್ವಜನಿಕ ಸಂಪರ್ಕವನ್ನು ಸಹ ಪ್ರದರ್ಶಿಸುತ್ತದೆ, ಸ್ಥಳೀಯ ಸಮುದಾಯಗಳು ಮತ್ತು ನಾಯಕರಿಂದ ಹೆಚ್ಚುತ್ತಿರುವ ಬೆಂಬಲವಿದೆ. ನಿರಂತರ ಸಂವಹನ ಮತ್ತು ವಕಾಲತ್ತುಗಳ ಮೂಲಕ, ಮಾಸ್ತಪ್ಪ ನಾಯ್ಕ ಬಲಸೆ ಅವರು ಅಭಿವೃದ್ಧಿ, ನ್ಯಾಯ ಮತ್ತು ಸಮಾಜದ ಯೋಗಕ್ಷೇಮದ ಮೇಲೆ ಕೇಂದ್ರೀಕರಿಸಿದ ಸಮರ್ಪಿತ ನಾಯಕರಾಗಿ ತಮ್ಮ ಪಾತ್ರವನ್ನು ಬಲಪಡಿಸುವುದನ್ನು ಮುಂದುವರಿಸಿದ್ದಾರೆ.",
    category: "Sharavathi Project & Environmental Movement"
  },
  {
    id: 20,
    url: "https://raw.githubusercontent.com/townlinksolutions/townlinksolutions/main/masthappna_naik/images/news/news20.jpg",
    titleEn: "Masthappa Naik Demands Accountability and Action on Public Issues",
    titleKn: "ಸಾರ್ವಜನಿಕ ಸಮಸ್ಯೆಗಳ ಕುರಿತು ಹೊಣೆಗಾರಿಕೆ ಮತ್ತು ಕ್ರಮಕ್ಕೆ ಮಾಸ್ತಪ್ಪ ನಾಯ್ಕ ಬಲಸೆ ಆಗ್ರಹ",
    shortDescEn: "Masthappa Naik highlights public issues and urges authorities to take swift, responsible action for the welfare of citizens.",
    shortDescKn: "ಮಾಸ್ತಪ್ಪ ನಾಯ್ಕ ಬಲಸೆ ಅವರು ಸಾರ್ವಜನಿಕ ಸಮಸ್ಯೆಗಳನ್ನು ಎತ್ತಿ ತೋರಿಸುತ್ತಾರೆ ಮತ್ತು ನಾಗರಿಕರ ಕಲ್ಯಾಣಕ್ಕಾಗಿ ಅಧಿಕಾರಿಗಳು ತ್ವರಿತ, ಜವಾಬ್ದಾರಿಯುತ ಕ್ರಮ ಕೈಗೊಳ್ಳುವಂತೆ ಒತ್ತಾಯಿಸುತ್ತಾರೆ.",
    contentEn: "As featured in this media report, Masthappa Naik addressed key concerns affecting the public and emphasized the urgent need for administrative action. He pointed out challenges faced by citizens at the grassroots level and called on responsible authorities to respond with efficiency and accountability.\n\nDuring his statement, he stressed the importance of transparent governance, proper implementation of policies, and timely resolution of issues impacting daily life. His approach reflects a commitment to ensuring that governance remains people-centric and responsive.\n\nThe report also showcases his growing influence and public connect, with increasing support from local communities and leaders. Through consistent engagement and advocacy, Masthappa Naik continues to reinforce his role as a dedicated leader focused on development, justice, and the well-being of society.",
    contentKn: "ಈ ಮಾಧ್ಯಮ ವರದಿಯಲ್ಲಿ ತೋರಿಸಿರುವಂತೆ, ಮಾಸ್ತಪ್ಪ ನಾಯ್ಕ ಬಲಸೆ ಅವರು ಸಾರ್ವಜನಿಕರನ್ನು ಬಾಧಿಸುವ ಪ್ರಮುಖ ಕಾಳಜಿಗಳನ್ನು ತಿಳಿಸಿದರು ಮತ್ತು ಆಡಳಿತಾತ್ಮಕ ಕ್ರಮದ ತುರ್ತು ಅಗತ್ಯವನ್ನು ಒತ್ತಿ ಹೇಳಿದರು. ಅವರು ತಳಮಟ್ಟದಲ್ಲಿ ನಾಗರಿಕರು ಎದುರಿಸುತ್ತಿರುವ ಸವಾಲುಗಳನ್ನು ಎತ್ತಿ ತೋರಿಸಿದರು ಮತ್ತು ಜವಾಬ್ದಾರಿಯುತ ಅಧಿಕಾರಿಗಳು ದಕ್ಷತೆ ಮತ್ತು ಹೊಣೆಗಾರಿಕೆಯೊಂದಿಗೆ ಸ್ಪಂದಿಸುವಂತೆ ಕರೆ ನೀಡಿದರು.\n\nತಮ್ಮ ಹೇಳಿಕೆಯ ಸಂದರ್ಭದಲ್ಲಿ, ಅವರು ಪಾರದರ್ಶಕ ಆಡಳಿತ, ನೀತಿಗಳ ಸರಿಯಾದ ಅನುಷ್ಠಾನ ಮತ್ತು ದೈನಂದಿನ ಜೀವನದ ಮೇಲೆ ಪರಿಣಾಮ ಬೀರುವ ಸಮಸ್ಯೆಗಳ ಸಮಯೋಚಿತ ಪರಿಹಾರದ ಮಹತ್ವವನ್ನು ಒತ್ತಿ ಹೇಳಿದರು. ಅವರ ವಿಧಾನವು ಆಡಳಿತವು ಜನಕೇಂದ್ರಿತವಾಗಿ ಮತ್ತು ಸ್ಪಂದಿಸುವಂತೆ ನೋಡಿಕೊಳ್ಳುವ ಬದ್ಧತೆಯನ್ನು ಪ್ರತಿಬಿಂಬಿಸುತ್ತದೆ.\n\nಈ ವರದಿಯು ಅವರ ಬೆಳೆಯುತ್ತಿರುವ ಪ್ರಭಾವ ಮತ್ತು ಸಾರ್ವಜನಿಕ ಸಂಪರ್ಕವನ್ನು ಸಹ ಪ್ರದರ್ಶಿಸುತ್ತದೆ, ಸ್ಥಳೀಯ ಸಮುದಾಯಗಳು ಮತ್ತು ನಾಯಕರಿಂದ ಹೆಚ್ಚುತ್ತಿರುವ ಬೆಂಬಲವಿದೆ. ನಿರಂತರ ಸಂವಹನ ಮತ್ತು ವಕಾಲತ್ತುಗಳ ಮೂಲಕ, ಮಾಸ್ತಪ್ಪ ನಾಯ್ಕ ಬಲಸೆ ಅವರು ಅಭಿವೃದ್ಧಿ, ನ್ಯಾಯ ಮತ್ತು ಸಮಾಜದ ಯೋಗಕ್ಷೇಮದ ಮೇಲೆ ಕೇಂದ್ರೀಕರಿಸಿದ ಸಮರ್ಪಿತ ನಾಯಕರಾಗಿ ತಮ್ಮ ಪಾತ್ರವನ್ನು ಬಲಪಡಿಸುವುದನ್ನು ಮುಂದುವರಿಸಿದ್ದಾರೆ.",
    category: "Mass Movements / Padayatra / Public Rallies"
  },
  {
    id: 21,
    url: "https://raw.githubusercontent.com/townlinksolutions/townlinksolutions/main/masthappna_naik/images/news/news21.jpg",
    titleEn: "High-Tension Debate at Sharavati Project Opposition Meeting",
    titleKn: "ಶರಾವತಿ ಯೋಜನೆ ವಿರೋಧಿ ಸಭೆಯಲ್ಲಿ ತೀವ್ರ ಚರ್ಚೆ",
    shortDescEn: "A report on the high-tension debate at the Sharavati project opposition meeting, where Masthappa Naik questioned the government's commitment and former MLA Sunil Naik issued a public apology.",
    shortDescKn: "ಶರಾವತಿ ಯೋಜನೆ ವಿರೋಧಿ ಸಭೆಯಲ್ಲಿ ನಡೆದ ತೀವ್ರ ಚರ್ಚೆಯ ವರದಿ, ಅಲ್ಲಿ ಮಾಸ್ತಪ್ಪ ನಾಯಕ್ ಸರ್ಕಾರದ ಬದ್ಧತೆಯನ್ನು ಪ್ರಶ್ನಿಸಿದರು ಮತ್ತು ಮಾಜಿ ಶಾಸಕ ಸುನಿಲ್ ನಾಯಕ್ ಸಾರ್ವಜನಿಕವಾಗಿ ಕ್ಷಮೆಯಾಚಿಸಿದರು.",
    contentEn: "The article covers the proceedings of the \"Sharavati Ulisi\" (Save Sharavati) convention at Munda Ganapati Hall, which saw a rare direct confrontation between social activists and high-ranking political leaders.\n\nKey Highlights:\nDemanding Administrative Action: The report details how Masthappa Naik Balle challenged District In-charge Minister Mankal Vaidya. He argued that instead of engaging in a \"blame game\" regarding which previous government started the project, the current administration should exercise its power to officially cancel it.\nAdmission of Past Mistakes: In a significant development, former MLA Sunil Naik stood before the public and religious leaders to apologize for the project's initial progress during his tenure. He admitted it was a mistake and joined the call for the current government to stop the project immediately.\nThe Voice of the People: Masthappa Naik emphasized that the 36-kilometer Padayatra was not a political stunt but a genuine expression of the people's fear of losing their forest and river. He dismissed allegations of \"social media politics,\" stating that the movement is rooted in the survival of the district’s ecosystem.\nSpiritual Guidance: The presence of various Swamijis (religious heads) provided a non-partisan weight to the event. They urged all political parties to set aside differences and unite to protect the Sharavati River, which they described as the \"soul of the region.\"\nFirm Resolution: The convention served as a platform to unify various factions of society, concluding with a collective oath to prevent any environmental destruction caused by the proposed Pumped Storage Project.",
    contentKn: "ಮುಂಡಾ ಗಣಪತಿ ಸಭಾಂಗಣದಲ್ಲಿ ನಡೆದ \"ಶರಾವತಿ ಉಳಿಸಿ\" ಸಮಾವೇಶದ ನಡಾವಳಿಗಳನ್ನು ಲೇಖನವು ಒಳಗೊಂಡಿದೆ, ಇದು ಸಾಮಾಜಿಕ ಕಾರ್ಯಕರ್ತರು ಮತ್ತು ಉನ್ನತ ಮಟ್ಟದ ರಾಜಕೀಯ ನಾಯಕರ ನಡುವಿನ ಅಪರೂಪದ ನೇರ ಮುಖಾಮುಖಿಯನ್ನು ಕಂಡಿತು. <br><br><strong>ಪ್ರಮುಖ ಅಂಶಗಳು:</strong><br> ಆಡಳಿತಾತ್ಮಕ ಕ್ರಮಕ್ಕೆ ಆಗ್ರಹ: ಮಾಸ್ತಪ್ಪ ನಾಯ್ಕ ಬಲಸೆ ಬಳ್ಳೆ ಅವರು ಜಿಲ್ಲಾ ಉಸ್ತುವಾರಿ ಸಚಿವ ಮಂಕಾಳ ವೈದ್ಯ ಅವರಿಗೆ ಹೇಗೆ ಸವಾಲು ಹಾಕಿದರು ಎಂಬುದನ್ನು ವರದಿ ವಿವರಿಸುತ್ತದೆ. ಹಿಂದಿನ ಯಾವ ಸರ್ಕಾರ ಯೋಜನೆಯನ್ನು ಪ್ರಾರಂಭಿಸಿತು ಎಂಬುದರ ಬಗ್ಗೆ \"ದೂಷಣೆ ಆಟ\" ದಲ್ಲಿ ತೊಡಗುವ ಬದಲು, ಪ್ರಸ್ತುತ ಆಡಳಿತವು ಅದನ್ನು ಅಧಿಕೃತವಾಗಿ ರದ್ದುಗೊಳಿಸಲು ತನ್ನ ಅಧಿಕಾರವನ್ನು ಚಲಾಯಿಸಬೇಕು ಎಂದು ಅವರು ವಾದಿಸಿದರು. ಹಿಂದಿನ ತಪ್ಪುಗಳ ಒಪ್ಪಿಗೆ: ಒಂದು ಮಹತ್ವದ ಬೆಳವಣಿಗೆಯಲ್ಲಿ, ಮಾಜಿ ಶಾಸಕ ಸುನಿಲ್ ನಾಯಕ್ ಅವರು ತಮ್ಮ ಅಧಿಕಾರಾವಧಿಯಲ್ಲಿ ಯೋಜನೆಯ ಆರಂಭಿಕ ಪ್ರಗತಿಗಾಗಿ ಕ್ಷಮೆಯಾಚಿಸಲು ಸಾರ್ವಜನಿಕ ಮತ್ತು ಧಾರ್ಮಿಕ ಮುಖಂಡರ ಮುಂದೆ ನಿಂತರು. ಇದು ಒಂದು ತಪ್ಪು ಎಂದು ಅವರು ಒಪ್ಪಿಕೊಂಡರು ಮತ್ತು ಯೋಜನೆಯನ್ನು ತಕ್ಷಣವೇ ನಿಲ್ಲಿಸುವಂತೆ ಪ್ರಸ್ತುತ ಸರ್ಕಾರಕ್ಕೆ ಕರೆ ನೀಡಿದರು. ಜನರ ಧ್ವನಿ: 36 ಕಿಲೋಮೀಟರ್ ಪಾದಯಾತ್ರೆಯು ರಾಜಕೀಯ ಗಿಮಿಕ್ ಅಲ್ಲ ಆದರೆ ತಮ್ಮ ಅರಣ್ಯ ಮತ್ತು ನದಿಯನ್ನು ಕಳೆದುಕೊಳ್ಳುವ ಜನರ ಭಯದ ನಿಜವಾದ ಅಭಿವ್ಯಕ್ತಿಯಾಗಿದೆ ಎಂದು ಮಾಸ್ತಪ್ಪ ನಾಯ್ಕ ಬಲಸೆ ಒತ್ತಿ ಹೇಳಿದರು. \"ಸಾಮಾಜಿಕ ಮಾಧ್ಯಮ ರಾಜಕೀಯ\" ದ ಆರೋಪಗಳನ್ನು ಅವರು ತಳ್ಳಿಹಾಕಿದರು, ಈ ಚಳುವಳಿಯು ಜಿಲ್ಲೆಯ ಪರಿಸರ ವ್ಯವಸ್ಥೆಯ ಉಳಿವಿಗಾಗಿ ಬೇರೂರಿದೆ ಎಂದು ಹೇಳಿದ್ದಾರೆ. ಆಧ್ಯಾತ್ಮಿಕ ಮಾರ್ಗದರ್ಶನ: ವಿವಿಧ ಸ್ವಾಮೀಜಿಗಳ (ಧಾರ್ಮಿಕ ಮುಖ್ಯಸ್ಥರು) ಉಪಸ್ಥಿತಿಯು ಕಾರ್ಯಕ್ರಮಕ್ಕೆ ಪಕ್ಷಾತೀತ ತೂಕವನ್ನು ಒದಗಿಸಿತು. ಎಲ್ಲಾ ರಾಜಕೀಯ ಪಕ್ಷಗಳು ಭಿನ್ನಾಭಿಪ್ರಾಯಗಳನ್ನು ಬದಿಗಿಟ್ಟು ಶರಾವತಿ ನದಿಯನ್ನು ರಕ್ಷಿಸಲು ಒಂದಾಗಬೇಕೆಂದು ಅವರು ಒತ್ತಾಯಿಸಿದರು, ಅದನ್ನು ಅವರು \"ಪ್ರದೇಶದ ಆತ್ಮ\" ಎಂದು ಬಣ್ಣಿಸಿದರು. ದೃಢವಾದ ನಿರ್ಣಯ: ಸಮಾವೇಶವು ಸಮಾಜದ ವಿವಿಧ ಬಣಗಳನ್ನು ಒಗ್ಗೂಡಿಸುವ ವೇದಿಕೆಯಾಗಿ ಕಾರ್ಯನಿರ್ವಹಿಸಿತು, ಪ್ರಸ್ತಾವಿತ ಪಂಪ್ಡ್ ಸ್ಟೋರೇಜ್ ಯೋಜನೆಯಿಂದ ಉಂಟಾಗುವ ಯಾವುದೇ ಪರಿಸರ ನಾಶವನ್ನು ತಡೆಯುವ ಸಾಮೂಹಿಕ ಪ್ರತಿಜ್ಞೆಯೊಂದಿಗೆ ಮುಕ್ತಾಯವಾಯಿತು.",
    category: "Sharavathi Project & Environmental Movement"
  },
  {
    id: 22,
    url: "https://raw.githubusercontent.com/townlinksolutions/townlinksolutions/main/masthappna_naik/images/news/news22.jpg",
    titleEn: "Demand for Official Apology at Sharavati Ulisi Convention",
    titleKn: "ಶರಾವತಿ ಉಳಿಸಿ ಸಮಾವೇಶದಲ್ಲಿ ಅಧಿಕೃತ ಕ್ಷಮೆಯಾಚನೆಗೆ ಆಗ್ರಹ",
    shortDescEn: "A report on the \"Sharavati Ulisi\" convention where Masthappa Naik accused District Minister Mankal Vaidya of misleading the public and religious leaders, demanding an official apology for his statements.",
    shortDescKn: "\"ಶರಾವತಿ ಉಳಿಸಿ\" ಸಮಾವೇಶದ ವರದಿ, ಅಲ್ಲಿ ಮಾಸ್ತಪ್ಪ ನಾಯಕ್ ಜಿಲ್ಲಾ ಸಚಿವ ಮಂಕಾಳ ವೈದ್ಯ ಅವರು ಸಾರ್ವಜನಿಕರನ್ನು ಮತ್ತು ಧಾರ್ಮಿಕ ಮುಖಂಡರನ್ನು ದಾರಿತಪ್ಪಿಸುತ್ತಿದ್ದಾರೆ ಎಂದು ಆರೋಪಿಸಿದರು ಮತ್ತು ಅವರ ಹೇಳಿಕೆಗಳಿಗಾಗಿ ಅಧಿಕೃತ ಕ್ಷಮೆಯಾಚಿಸುವಂತೆ ಒತ್ತಾಯಿಸಿದರು.",
    contentEn: "The convention held at Munda Ganapati Hall served as a focal point for environmental resistance, but it was also marked by a severe verbal confrontation between activists and the government. <br><br><strong>Key Highlights:</strong><br> <strong>Allegations of Falsehood:</strong> In News 21 and 23, Masthappa Naik Balle issued a strong press statement claiming that Minister Mankal Vaidya lied on stage in the presence of revered Swamijis. Specifically, the Minister claimed that Deputy CM D.K. Shivakumar had not spoken about the project during his Karwar visit, whereas viral videos allegedly prove otherwise. <strong>Demand for Apology:</strong> Masthappa Naik stated that speaking untruths in front of religious heads like Shree Raghaveshwara Bharathi Swamiji and Shree Maruthi Guruji is an insult to the sanctity of the stage and the people's trust. He demanded that the Minister issue a public apology. \No to Sharavati Project\: News 22 (Munjavu) captures the unified voice of religious and political leaders. Shree Raghaveshwara Bharathi Swamiji declared that the Sharavati River is the \"soul of the region\" and its natural flow must not be tampered with for any \"unscientific\" pumped storage project. <strong>United Political Resistance:</strong> The reports mention that leaders from various parties—including former ministers and MLAs like Shivanand Hegde and Sunil Naik—joined the chorus, stating that they would set aside party politics to ensure the project is scrapped. <strong>Public Outcry:</strong> The convention highlighted that the project would be disastrous for the local ecosystem, drinking water, and the livelihoods of fishermen and farmers in the Bhatkal and Honnavar taluks.",
    contentKn: "ಮುಂಡಾ ಗಣಪತಿ ಸಭಾಂಗಣದಲ್ಲಿ ನಡೆದ ಸಮಾವೇಶವು ಪರಿಸರ ಪ್ರತಿರೋಧದ ಕೇಂದ್ರಬಿಂದುವಾಗಿ ಕಾರ್ಯನಿರ್ವಹಿಸಿತು, ಆದರೆ ಇದು ಕಾರ್ಯಕರ್ತರು ಮತ್ತು ಸರ್ಕಾರದ ನಡುವಿನ ತೀವ್ರ ಮೌಖಿಕ ಮುಖಾಮುಖಿಯಿಂದ ಕೂಡ ಗುರುತಿಸಲ್ಪಟ್ಟಿದೆ. <br><br><strong>ಪ್ರಮುಖ ಅಂಶಗಳು:</strong><br> ಸುಳ್ಳಿನ ಆರೋಪಗಳು: ಪೂಜ್ಯ ಸ್ವಾಮೀಜಿಗಳ ಸಮ್ಮುಖದಲ್ಲಿ ಸಚಿವ ಮಂಕಾಳ ವೈದ್ಯ ವೇದಿಕೆಯ ಮೇಲೆ ಸುಳ್ಳು ಹೇಳಿದ್ದಾರೆ ಎಂದು ಮಾಸ್ತಪ್ಪ ನಾಯ್ಕ ಬಲಸೆ ಬಳ್ಳೆ ಬಲವಾದ ಪತ್ರಿಕಾ ಹೇಳಿಕೆ ನೀಡಿದ್ದಾರೆ. ನಿರ್ದಿಷ್ಟವಾಗಿ ಹೇಳುವುದಾದರೆ, ಉಪಮುಖ್ಯಮಂತ್ರಿ ಡಿ.ಕೆ. ಶಿವಕುಮಾರ್ ಅವರು ತಮ್ಮ ಕಾರವಾರ ಭೇಟಿಯ ಸಂದರ್ಭದಲ್ಲಿ ಯೋಜನೆಯ ಬಗ್ಗೆ ಮಾತನಾಡಿಲ್ಲ ಎಂದು ಸಚಿವರು ಹೇಳಿದ್ದಾರೆ, ಆದರೆ ವೈರಲ್ ವೀಡಿಯೊಗಳು ಬೇರೆ ರೀತಿಯಲ್ಲಿ ಸಾಬೀತುಪಡಿಸುತ್ತವೆ. ಕ್ಷಮೆಯಾಚನೆಗೆ ಆಗ್ರಹ: ಶ್ರೀ ರಾಘವೇಶ್ವರ ಭಾರತಿ ಸ್ವಾಮೀಜಿ ಮತ್ತು ಶ್ರೀ ಮಾರುತಿ ಗುರೂಜಿಯಂತಹ ಧಾರ್ಮಿಕ ಮುಖಂಡರ ಮುಂದೆ ಸುಳ್ಳು ಹೇಳುವುದು ವೇದಿಕೆಯ ಪಾವಿತ್ರ್ಯತೆ ಮತ್ತು ಜನರ ನಂಬಿಕೆಗೆ ಮಾಡಿದ ಅವಮಾನ ಎಂದು ಮಾಸ್ತಪ್ಪ ನಾಯ್ಕ ಬಲಸೆ ಹೇಳಿದ್ದಾರೆ. ಸಚಿವರು ಸಾರ್ವಜನಿಕವಾಗಿ ಕ್ಷಮೆಯಾಚಿಸಬೇಕು ಎಂದು ಅವರು ಒತ್ತಾಯಿಸಿದರು. \ಶರಾವತಿ ಯೋಜನೆಗೆ ಇಲ್ಲ\: ಧಾರ್ಮಿಕ ಮತ್ತು ರಾಜಕೀಯ ನಾಯಕರ ಏಕೀಕೃತ ಧ್ವನಿಯನ್ನು ವರದಿ ಸೆರೆಹಿಡಿಯುತ್ತದೆ. ಶರಾವತಿ ನದಿಯು \"ಪ್ರದೇಶದ ಆತ್ಮ\" ಮತ್ತು ಯಾವುದೇ \"ಅವೈಜ್ಞಾನಿಕ\" ಪಂಪ್ಡ್ ಸ್ಟೋರೇಜ್ ಯೋಜನೆಗಾಗಿ ಅದರ ನೈಸರ್ಗಿಕ ಹರಿವನ್ನು ಹಾಳುಮಾಡಬಾರದು ಎಂದು ಶ್ರೀ ರಾಘವೇಶ್ವರ ಭಾರತಿ ಸ್ವಾಮೀಜಿ ಘೋಷಿಸಿದರು. ಯುನೈಟೆಡ್ ರಾಜಕೀಯ ಪ್ರತಿರೋಧ: ಮಾಜಿ ಸಚಿವರು ಮತ್ತು ಶಾಸಕರಾದ ಶಿವಾನಂದ ಹೆಗಡೆ ಮತ್ತು ಸುನಿಲ್ ನಾಯಕ್ ಸೇರಿದಂತೆ ವಿವಿಧ ಪಕ್ಷಗಳ ನಾಯಕರು, ಯೋಜನೆಯನ್ನು ರದ್ದುಗೊಳಿಸುವುದನ್ನು ಖಚಿತಪಡಿಸಿಕೊಳ್ಳಲು ಪಕ್ಷದ ರಾಜಕೀಯವನ್ನು ಬದಿಗಿಡುವುದಾಗಿ ಹೇಳಿದ್ದಾರೆ. ಸಾರ್ವಜನಿಕ ಆಕ್ರೋಶ: ಈ ಯೋಜನೆಯು ಸ್ಥಳೀಯ ಪರಿಸರ ವ್ಯವಸ್ಥೆ, ಕುಡಿಯುವ ನೀರು ಮತ್ತು ಭಟ್ಕಳ ಮತ್ತು ಹೊನ್ನಾವರ ತಾಲೂಕುಗಳ ಮೀನುಗಾರರು ಮತ್ತು ರೈತರ ಜೀವನೋಪಾಯಕ್ಕೆ ವಿನಾಶಕಾರಿಯಾಗಿದೆ ಎಂದು ಸಮಾವೇಶವು ಎತ್ತಿ ತೋರಿಸಿದೆ.",
    category: "Sharavathi Project & Environmental Movement"
  },
  {
    id: 23,
    url: "https://raw.githubusercontent.com/townlinksolutions/townlinksolutions/main/masthappna_naik/images/news/news23.jpg",
    titleEn: "Truth vs. <strong>Politics:</strong> The Viral Video Dispute",
    titleKn: "ಸತ್ಯ vs ರಾಜಕೀಯ: ವೈರಲ್ ವೀಡಿಯೊ ವಿವಾದ",
    shortDescEn: "A report on the escalating confrontation between Masthappa Naik and Minister Mankal Vaidya over Deputy CM D.K. Shivakumar’s viral video regarding the Sharavati project, titled: \"Truth vs. Politics.\"",
    shortDescKn: "ಶರಾವತಿ ಯೋಜನೆಗೆ ಸಂಬಂಧಿಸಿದಂತೆ ಉಪಮುಖ್ಯಮಂತ್ರಿ ಡಿ.ಕೆ. ಶಿವಕುಮಾರ್ ಅವರ ವೈರಲ್ ವೀಡಿಯೊ ಕುರಿತು ಮಾಸ್ತಪ್ಪ ನಾಯ್ಕ ಬಲಸೆ ಮತ್ತು ಸಚಿವ ಮಂಕಾಳ ವೈದ್ಯ ನಡುವಿನ ಹೆಚ್ಚುತ್ತಿರುವ ಮುಖಾಮುಖಿಯ ವರದಿ: \"ಸತ್ಯ vs ರಾಜಕೀಯ.\"",
    contentEn: "The news article highlights a significant credibility crisis stemming from the public convention in Honnavar. It focuses on the clash between political narratives and digital evidence. <br><br><strong>Key Highlights:</strong><br> <strong>The Viral Video Dispute:</strong> The headline—\"<strong>Mankal Vaidya and Masthappa Naik Clash:</strong> D.K. Shivakumar’s Sharavati Statement Goes Viral Again\"—refers to a specific video where the Deputy CM allegedly spoke in favor of the Sharavati Pumped Storage Project. Minister Mankal Vaidya had claimed on stage that no such statement was made, but activists have used the video to challenge his honesty. <strong>Direct Challenge:</strong> Masthappa Naik Balle argued that speaking untruths in the presence of revered Swamijis is a betrayal of public trust. He challenged the Minister to watch the video evidence and explain why the government’s stance seems to differ between closed-door meetings and public platforms. Minister’s <strong>Retort:</strong> The report notes that Minister Mankal Vaidya reacted with frustration, accusing his opponents of trying to \"troll\" him and using social media to create unnecessary controversy. He maintained that his primary focus remains the development of the district and that the project is a legacy of the previous administration. <strong>Public and Spiritual Outcry:</strong> The article mentions that religious leaders like Maruthi Guruji have noticed the inconsistency in political statements. The community is increasingly skeptical of politicians who \"change their words\" based on the audience. <strong>The Impact on the Movement:</strong> This \"video war\" has energized the local youth and environmentalists, who are now using digital tools to hold representatives accountable. It has turned the Sharavati project into a high-stakes battle for transparency in Uttara Kannada.",
    contentKn: "ಹೊನ್ನಾವರದಲ್ಲಿ ನಡೆದ ಸಾರ್ವಜನಿಕ ಸಮಾವೇಶದಿಂದ ಉಂಟಾದ ಗಮನಾರ್ಹ ವಿಶ್ವಾಸಾರ್ಹತೆಯ ಬಿಕ್ಕಟ್ಟನ್ನು ಸುದ್ದಿ ಲೇಖನ ಎತ್ತಿ ತೋರಿಸುತ್ತದೆ. ಇದು ರಾಜಕೀಯ ನಿರೂಪಣೆಗಳು ಮತ್ತು ಡಿಜಿಟಲ್ ಪುರಾವೆಗಳ ನಡುವಿನ ಘರ್ಷಣೆಯ ಮೇಲೆ ಕೇಂದ್ರೀಕರಿಸುತ್ತದೆ. <br><br><strong>ಪ್ರಮುಖ ಅಂಶಗಳು:</strong><br> ವೈರಲ್ ವೀಡಿಯೊ ವಿವಾದ: \"ಮಂಕಾಳ ವೈದ್ಯ ಮತ್ತು ಮಾಸ್ತಪ್ಪ ನಾಯ್ಕ ಬಲಸೆ ಘರ್ಷಣೆ: ಡಿ.ಕೆ. ಶಿವಕುಮಾರ್ ಅವರ ಶರಾವತಿ ಹೇಳಿಕೆ ಮತ್ತೆ ವೈರಲ್\" ಎಂಬ ತಲೆಬರಹವು ಉಪಮುಖ್ಯಮಂತ್ರಿಗಳು ಶರಾವತಿ ಪಂಪ್ಡ್ ಸ್ಟೋರೇಜ್ ಯೋಜನೆಗೆ ಒಲವು ತೋರಿದ್ದಾರೆ ಎನ್ನಲಾದ ನಿರ್ದಿಷ್ಟ ವೀಡಿಯೊವನ್ನು ಉಲ್ಲೇಖಿಸುತ್ತದೆ. ಸಚಿವ ಮಂಕಾಳ ವೈದ್ಯ ಅವರು ವೇದಿಕೆಯ ಮೇಲೆ ಅಂತಹ ಯಾವುದೇ ಹೇಳಿಕೆ ನೀಡಿಲ್ಲ ಎಂದು ಹೇಳಿದ್ದರು, ಆದರೆ ಕಾರ್ಯಕರ್ತರು ಅವರ ಪ್ರಾಮಾಣಿಕತೆಯನ್ನು ಪ್ರಶ್ನಿಸಲು ವೀಡಿಯೊವನ್ನು ಬಳಸಿದ್ದಾರೆ. ನೇರ ಸವಾಲು: ಪೂಜ್ಯ ಸ್ವಾಮೀಜಿಗಳ ಸಮ್ಮುಖದಲ್ಲಿ ಸುಳ್ಳು ಹೇಳುವುದು ಸಾರ್ವಜನಿಕ ನಂಬಿಕೆಯ ದ್ರೋಹ ಎಂದು ಮಾಸ್ತಪ್ಪ ನಾಯ್ಕ ಬಲಸೆ ಬಳ್ಳೆ ವಾದಿಸಿದರು. ವೀಡಿಯೊ ಸಾಕ್ಷ್ಯವನ್ನು ವೀಕ್ಷಿಸಲು ಮತ್ತು ಮುಚ್ಚಿದ ಬಾಗಿಲಿನ ಸಭೆಗಳು ಮತ್ತು ಸಾರ್ವಜನಿಕ ವೇದಿಕೆಗಳ ನಡುವೆ ಸರ್ಕಾರದ ನಿಲುವು ಏಕೆ ಭಿನ್ನವಾಗಿದೆ ಎಂಬುದನ್ನು ವಿವರಿಸಲು ಅವರು ಸಚಿವರಿಗೆ ಸವಾಲು ಹಾಕಿದರು. ಸಚಿವರ ತಿರುಗೇಟು: ಸಚಿವ ಮಂಕಾಳ ವೈದ್ಯ ಹತಾಶೆಯಿಂದ ಪ್ರತಿಕ್ರಿಯಿಸಿದ್ದಾರೆ, ತಮ್ಮ ವಿರೋಧಿಗಳು ತಮ್ಮನ್ನು \"ಟ್ರೋಲ್\" ಮಾಡಲು ಪ್ರಯತ್ನಿಸುತ್ತಿದ್ದಾರೆ ಮತ್ತು ಅನಗತ್ಯ ವಿವಾದವನ್ನು ಸೃಷ್ಟಿಸಲು ಸಾಮಾಜಿಕ ಮಾಧ್ಯಮವನ್ನು ಬಳಸುತ್ತಿದ್ದಾರೆ ಎಂದು ಆರೋಪಿಸಿದ್ದಾರೆ. ಜಿಲ್ಲೆಯ ಅಭಿವೃದ್ಧಿಯೇ ತಮ್ಮ ಪ್ರಾಥಮಿಕ ಗಮನ ಮತ್ತು ಈ ಯೋಜನೆಯು ಹಿಂದಿನ ಆಡಳಿತದ ಕೊಡುಗೆಯಾಗಿದೆ ಎಂದು ಅವರು ಪ್ರತಿಪಾದಿಸಿದರು. ಸಾರ್ವಜನಿಕ ಮತ್ತು ಆಧ್ಯಾತ್ಮಿಕ ಆಕ್ರೋಶ: ರಾಜಕೀಯ ಹೇಳಿಕೆಗಳಲ್ಲಿನ ಅಸಂಗತತೆಯನ್ನು ಮಾರುತಿ ಗುರೂಜಿಯಂತಹ ಧಾರ್ಮಿಕ ಮುಖಂಡರು ಗಮನಿಸಿದ್ದಾರೆ ಎಂದು ಲೇಖನ ಉಲ್ಲೇಖಿಸುತ್ತದೆ. ಪ್ರೇಕ್ಷಕರನ್ನು ಆಧರಿಸಿ \"ತಮ್ಮ ಮಾತುಗಳನ್ನು ಬದಲಾಯಿಸುವ\" ರಾಜಕಾರಣಿಗಳ ಬಗ್ಗೆ ಸಮುದಾಯವು ಹೆಚ್ಚು ಸಂದೇಹ ವ್ಯಕ್ತಪಡಿಸುತ್ತಿದೆ. ಚಳುವಳಿಯ ಮೇಲಿನ ಪ್ರಭಾವ: ಈ \"ವೀಡಿಯೊ ಯುದ್ಧ\" ಸ್ಥಳೀಯ ಯುವಕರು ಮತ್ತು ಪರಿಸರವಾದಿಗಳನ್ನು ಉತ್ತೇಜಿಸಿದೆ, ಅವರು ಈಗ ಪ್ರತಿನಿಧಿಗಳನ್ನು ಹೊಣೆಗಾರರನ್ನಾಗಿ ಮಾಡಲು ಡಿಜಿಟಲ್ ಸಾಧನಗಳನ್ನು ಬಳಸುತ್ತಿದ್ದಾರೆ. ಇದು ಶರಾವತಿ ಯೋಜನೆಯನ್ನು ಉತ್ತರ ಕನ್ನಡದಲ್ಲಿ ಪಾರದರ್ಶಕತೆಗಾಗಿ ಹೆಚ್ಚಿನ ಹಕ್ಕಿನ ಯುದ್ಧವನ್ನಾಗಿ ಮಾಡಿದೆ.",
    category: "Sharavathi Project & Environmental Movement"
  },
  {
    id: 24,
    url: "https://raw.githubusercontent.com/townlinksolutions/townlinksolutions/main/masthappna_naik/images/news/news24.jpg",
    titleEn: "Legal Status of Sharavati Project and Critique of Minister",
    titleKn: "ಶರಾವತಿ ಯೋಜನೆಯ ಕಾನೂನು ಸ್ಥಿತಿ ಮತ್ತು ಸಚಿವರ ಟೀಕೆ",
    shortDescEn: "A detailed report on the legal status of the Sharavati Pumped Storage Project in court and Masthappa Naik’s ongoing critique of Minister Mankal Vaidya’s conduct at the Honnavar convention.",
    shortDescKn: "ನ್ಯಾಯಾಲಯದಲ್ಲಿ ಶರಾವತಿ ಪಂಪ್ಡ್ ಸ್ಟೋರೇಜ್ ಯೋಜನೆಯ ಕಾನೂನು ಸ್ಥಿತಿ ಮತ್ತು ಹೊನ್ನಾವರ ಸಮಾವೇಶದಲ್ಲಿ ಸಚಿವ ಮಂಕಾಳ ವೈದ್ಯ ಅವರ ನಡವಳಿಕೆಯ ಕುರಿತು ಮಾಸ್ತಪ್ಪ ನಾಯಕ್ ಅವರ ನಿರಂತರ ಟೀಕೆಯ ವಿವರವಾದ ವರದಿ.",
    contentEn: "The article provides a multi-faceted update on the Sharavati struggle, touching upon both judicial proceedings and the political fallout from the recent public convention.\n\nKey Highlights:\nLegal Roadblocks: The report mentions that the project lacks approval from the National Board for Wildlife. Solicitor General Arvind Kamath stated that the concerns regarding the wildlife sanctuary are being reviewed. Furthermore, it is highlighted that under Section 29 of the Wildlife Protection Act, 1972, no project should be approved that destroys the habitat of a sanctuary, which the petitioners are using to stall the project.\nMasthappa Naik vs. Minister Vaidya: Under the subheading \"Masthappa against Minister Vaidya,\" the article covers a press release where Naik accuses the Minister of \"double-dealing\" politics. He reiterated that the Minister spoke untruths regarding Deputy CM D.K. Shivakumar’s stance in front of religious leaders like Shree Raghaveshwara Swamiji and Maruthi Guruji.\nThe \"Fake ID\" Allegation: Naik posed a serious question to the Minister: Why are personal matters and \"fake social media IDs\" being discussed at a convention meant to save a river? He alleged that people close to the Minister are using these digital tools for character assassination instead of addressing the project's environmental impact.\nAdministrative Defense: The article also includes the Minister's response, where he claims he is personally opposed to the project and has informed his party leaders, but certain elements are playing \"petty politics\" to confuse the public.",
    contentKn: "ಲೇಖನವು ಶರಾವತಿ ಹೋರಾಟದ ಬಹುಮುಖಿ ನವೀಕರಣವನ್ನು ಒದಗಿಸುತ್ತದೆ, ನ್ಯಾಯಾಂಗ ಪ್ರಕ್ರಿಯೆಗಳು ಮತ್ತು ಇತ್ತೀಚಿನ ಸಾರ್ವಜನಿಕ ಸಮಾವೇಶದ ರಾಜಕೀಯ ಪರಿಣಾಮಗಳನ್ನು ಸ್ಪರ್ಶಿಸುತ್ತದೆ. <br><br><strong>ಪ್ರಮುಖ ಅಂಶಗಳು:</strong><br> ಕಾನೂನು ಅಡೆತಡೆಗಳು: ಯೋಜನೆಗೆ ರಾಷ್ಟ್ರೀಯ ವನ್ಯಜೀವಿ ಮಂಡಳಿಯ ಅನುಮೋದನೆ ಇಲ್ಲ ಎಂದು ವರದಿ ಉಲ್ಲೇಖಿಸಿದೆ. ವನ್ಯಜೀವಿ ಅಭಯಾರಣ್ಯದ ಕಾಳಜಿಯನ್ನು ಪರಿಶೀಲಿಸಲಾಗುತ್ತಿದೆ ಎಂದು ಸಾಲಿಸಿಟರ್ ಜನರಲ್ ಅರವಿಂದ್ ಕಾಮತ್ ಹೇಳಿದ್ದಾರೆ. ಇದಲ್ಲದೆ, 1972 ರ ವನ್ಯಜೀವಿ ಸಂರಕ್ಷಣಾ ಕಾಯ್ದೆಯ ಸೆಕ್ಷನ್ 29 ರ ಅಡಿಯಲ್ಲಿ, ಅಭಯಾರಣ್ಯದ ಆವಾಸಸ್ಥಾನವನ್ನು ನಾಶಪಡಿಸುವ ಯಾವುದೇ ಯೋಜನೆಗೆ ಅನುಮೋದನೆ ನೀಡಬಾರದು ಎಂದು ಎತ್ತಿ ತೋರಿಸಲಾಗಿದೆ, ಇದನ್ನು ಅರ್ಜಿದಾರರು ಯೋಜನೆಯನ್ನು ತಡೆಯಲು ಬಳಸುತ್ತಿದ್ದಾರೆ. ಮಾಸ್ತಪ್ಪ ನಾಯಕ್ ವಿರುದ್ಧ ಸಚಿವ ವೈದ್ಯ: \"ಸಚಿವ ವೈದ್ಯರ ವಿರುದ್ಧ ಮಾಸ್ತಪ್ಪ\" ಎಂಬ ಉಪಶೀರ್ಷಿಕೆಯಡಿಯಲ್ಲಿ, ಲೇಖನವು ಪತ್ರಿಕಾ ಪ್ರಕಟಣೆಯನ್ನು ಒಳಗೊಂಡಿದೆ, ಅಲ್ಲಿ ನಾಯಕ್ ಸಚಿವರ ಮೇಲೆ \"ದ್ವಂದ್ವ\" ರಾಜಕೀಯದ ಆರೋಪ ಮಾಡಿದ್ದಾರೆ. ಶ್ರೀ ರಾಘವೇಶ್ವರ ಸ್ವಾಮೀಜಿ ಮತ್ತು ಮಾರುತಿ ಗುರೂಜಿಯಂತಹ ಧಾರ್ಮಿಕ ಮುಖಂಡರ ಮುಂದೆ ಉಪಮುಖ್ಯಮಂತ್ರಿ ಡಿ.ಕೆ. ಶಿವಕುಮಾರ್ ಅವರ ನಿಲುವಿನ ಬಗ್ಗೆ ಸಚಿವರು ಸುಳ್ಳು ಹೇಳಿದ್ದಾರೆ ಎಂದು ಅವರು ಪುನರುಚ್ಚರಿಸಿದರು. \"ನಕಲಿ ಐಡಿ\" ಆರೋಪ: ನಾಯಕ್ ಸಚಿವರಿಗೆ ಗಂಭೀರ ಪ್ರಶ್ನೆಯೊಂದನ್ನು ಮುಂದಿಟ್ಟರು: ನದಿಯನ್ನು ಉಳಿಸುವ ಉದ್ದೇಶದಿಂದ ನಡೆಯುತ್ತಿರುವ ಸಮಾವೇಶದಲ್ಲಿ ವೈಯಕ್ತಿಕ ವಿಷಯಗಳು ಮತ್ತು \"ನಕಲಿ ಸಾಮಾಜಿಕ ಮಾಧ್ಯಮ ಐಡಿಗಳನ್ನು\" ಏಕೆ ಚರ್ಚಿಸಲಾಗುತ್ತಿದೆ? ಯೋಜನೆಯ ಪರಿಸರ ಪ್ರಭಾವವನ್ನು ಪರಿಹರಿಸುವ ಬದಲು ಸಚಿವರಿಗೆ ಆಪ್ತರಾದವರು ಈ ಡಿಜಿಟಲ್ ಸಾಧನಗಳನ್ನು ತೇಜೋವಧೆ ಮಾಡಲು ಬಳಸುತ್ತಿದ್ದಾರೆ ಎಂದು ಅವರು ಆರೋಪಿಸಿದರು. ಆಡಳಿತಾತ್ಮಕ ರಕ್ಷಣೆ: ಲೇಖನವು ಸಚಿವರ ಪ್ರತಿಕ್ರಿಯೆಯನ್ನು ಸಹ ಒಳಗೊಂಡಿದೆ, ಅಲ್ಲಿ ಅವರು ವೈಯಕ್ತಿಕವಾಗಿ ಯೋಜನೆಯನ್ನು ವಿರೋಧಿಸುತ್ತಾರೆ ಮತ್ತು ತಮ್ಮ ಪಕ್ಷದ ನಾಯಕರಿಗೆ ತಿಳಿಸಿದ್ದಾರೆ ಎಂದು ಹೇಳಿಕೊಳ್ಳುತ್ತಾರೆ, ಆದರೆ ಕೆಲವು ಅಂಶಗಳು ಸಾರ್ವಜನಿಕರನ್ನು ಗೊಂದಲಕ್ಕೀಡು ಮಾಡಲು \"ಕ್ಷುಲ್ಲಕ ರಾಜಕೀಯ\" ಮಾಡುತ್ತಿವೆ.",
    category: "Sharavathi Project & Environmental Movement"
  },
  {
    id: 25,
    url: "https://raw.githubusercontent.com/townlinksolutions/townlinksolutions/main/masthappna_naik/images/news/news25.jpg",
    titleEn: "Demand for Minister's Apology Over Sharavati Project",
    titleKn: "ಶರಾವತಿ ಯೋಜನೆ ಕುರಿತು ಸಚಿವರ ಕ್ಷಮೆಯಾಚನೆಗೆ ಆಗ್ರಹ",
    shortDescEn: "A report on Masthappa Naik’s direct challenge to Minister Mankal Vaidya, calling for an apology after the Minister allegedly misled the public and religious leaders regarding the Sharavati project.",
    shortDescKn: "ಶರಾವತಿ ಯೋಜನೆಗೆ ಸಂಬಂಧಿಸಿದಂತೆ ಸಾರ್ವಜನಿಕರು ಮತ್ತು ಧಾರ್ಮಿಕ ಮುಖಂಡರನ್ನು ದಾರಿತಪ್ಪಿಸಿದ ಆರೋಪದ ಮೇಲೆ ಸಚಿವ ಮಂಕಾಳ ವೈದ್ಯ ಅವರಿಗೆ ಮಾಸ್ತಪ್ಪ ನಾಯಕ್ ಅವರ ನೇರ ಸವಾಲು, ಕ್ಷಮೆಯಾಚಿಸುವಂತೆ ಒತ್ತಾಯಿಸಿದ ವರದಿ.",
    contentEn: "The article highlights the aftermath of the \"Sharavati Ulisi\" convention, focusing on the ethical and political fallout from the District In-charge Minister's statements. <br><br><strong>Key Highlights:</strong><br> <strong>Demanding Accountability:</strong> The headline—\"<strong>Minister Mankal Vaidya should apologize for lying in front of Swamiji:</strong> Masthappa Naik\"—underlines the activist's firm stance. Masthappa Naik Balle argued that a leader's integrity is compromised when they speak untruthfully in the presence of spiritual guides like Shree Raghaveshwara Swamiji. The \"Video\" <strong>Evidence:</strong> The report reiterates the controversy surrounding Deputy CM D.K. Shivakumar’s statements. Masthappa Naik alleged that the Minister's denial of the viral video was a \"shameful act\" that insulted the intelligence of the gathered public. <strong>Critique of Political Character:</strong> Naik expressed that instead of focusing on the core environmental issues, the Minister and his associates are resorting to \"character assassination\" and \"fake social media IDs\" to divert public attention. <strong>Focus on the Sharavati River:</strong> He emphasized that the movement is not personal; it is a collective struggle to protect the Sharavati River from unscientific projects that threaten the district's future. <strong>Call for Administrative Clarity:</strong> The activist urged the Minister to stop the \"blame game\" and provide a documented cabinet decision to officially scrap the Sharavati Pumped Storage Project.",
    contentKn: "ಲೇಖನವು \"ಶರಾವತಿ ಉಳಿಸಿ\" ಸಮಾವೇಶದ ನಂತರದ ಪರಿಣಾಮಗಳನ್ನು ಎತ್ತಿ ತೋರಿಸುತ್ತದೆ, ಜಿಲ್ಲಾ ಉಸ್ತುವಾರಿ ಸಚಿವರ ಹೇಳಿಕೆಗಳಿಂದ ಉಂಟಾದ ನೈತಿಕ ಮತ್ತು ರಾಜಕೀಯ ಪರಿಣಾಮಗಳ ಮೇಲೆ ಕೇಂದ್ರೀಕರಿಸುತ್ತದೆ. <br><br><strong>ಪ್ರಮುಖ ಅಂಶಗಳು:</strong><br> ಹೊಣೆಗಾರಿಕೆಗೆ ಆಗ್ರಹ: \"ಸ್ವಾಮೀಜಿಗಳ ಮುಂದೆ ಸುಳ್ಳು ಹೇಳಿದ್ದಕ್ಕಾಗಿ ಸಚಿವ ಮಂಕಾಳ ವೈದ್ಯ ಕ್ಷಮೆಯಾಚಿಸಬೇಕು: ಮಾಸ್ತಪ್ಪ ನಾಯಕ್\" ಎಂಬ ತಲೆಬರಹವು ಕಾರ್ಯಕರ್ತರ ದೃಢವಾದ ನಿಲುವನ್ನು ಒತ್ತಿಹೇಳುತ್ತದೆ. ಶ್ರೀ ರಾಘವೇಶ್ವರ ಸ್ವಾಮೀಜಿಯಂತಹ ಆಧ್ಯಾತ್ಮಿಕ ಮಾರ್ಗದರ್ಶಕರ ಸಮ್ಮುಖದಲ್ಲಿ ಅಸತ್ಯವಾಗಿ ಮಾತನಾಡುವಾಗ ನಾಯಕನ ಸಮಗ್ರತೆಗೆ ಧಕ್ಕೆಯಾಗುತ್ತದೆ ಎಂದು ಮಾಸ್ತಪ್ಪ ನಾಯಕ್ ಬಳ್ಳೆ ವಾದಿಸಿದರು. \"ವೀಡಿಯೊ\" ಸಾಕ್ಷ್ಯ: ಉಪಮುಖ್ಯಮಂತ್ರಿ ಡಿ.ಕೆ. ಶಿವಕುಮಾರ್ ಅವರ ಹೇಳಿಕೆಗಳ ಸುತ್ತಲಿನ ವಿವಾದವನ್ನು ವರದಿ ಪುನರುಚ್ಚರಿಸುತ್ತದೆ. ವೈರಲ್ ವೀಡಿಯೊವನ್ನು ಸಚಿವರು ನಿರಾಕರಿಸಿದ್ದು ನೆರೆದಿದ್ದ ಸಾರ್ವಜನಿಕರ ಬುದ್ಧಿಮತ್ತೆಯನ್ನು ಅವಮಾನಿಸುವ \"ನಾಚಿಕೆಗೇಡಿನ ಕೃತ್ಯ\" ಎಂದು ಮಾಸ್ತಪ್ಪ ನಾಯಕ್ ಆರೋಪಿಸಿದರು. ರಾಜಕೀಯ ನಡವಳಿಕೆಯ ಟೀಕೆ: ಪ್ರಮುಖ ಪರಿಸರ ಸಮಸ್ಯೆಗಳತ್ತ ಗಮನ ಹರಿಸುವ ಬದಲು, ಸಚಿವರು ಮತ್ತು ಅವರ ಸಹಚರರು ಸಾರ್ವಜನಿಕರ ಗಮನವನ್ನು ಬೇರೆಡೆ ಸೆಳೆಯಲು \"ತೇಜೋವಧೆ\" ಮತ್ತು \"ನಕಲಿ ಸಾಮಾಜಿಕ ಮಾಧ್ಯಮ ಐಡಿಗಳನ್ನು\" ಆಶ್ರಯಿಸುತ್ತಿದ್ದಾರೆ ಎಂದು ನಾಯಕ್ ವ್ಯಕ್ತಪಡಿಸಿದರು. ಶರಾವತಿ ನದಿಯ ಮೇಲೆ ಗಮನ: ಈ ಚಳುವಳಿಯು ವೈಯಕ್ತಿಕವಲ್ಲ; ಜಿಲ್ಲೆಯ ಭವಿಷ್ಯಕ್ಕೆ ಬೆದರಿಕೆ ಒಡ್ಡುವ ಅವೈಜ್ಞಾನಿಕ ಯೋಜನೆಗಳಿಂದ ಶರಾವತಿ ನದಿಯನ್ನು ರಕ್ಷಿಸುವ ಸಾಮೂಹಿಕ ಹೋರಾಟವಾಗಿದೆ ಎಂದು ಅವರು ಒತ್ತಿ ಹೇಳಿದರು. ಆಡಳಿತಾತ್ಮಕ ಸ್ಪಷ್ಟತೆಗೆ ಕರೆ: \"ದೂಷಣೆ ಆಟ\" ವನ್ನು ನಿಲ್ಲಿಸುವಂತೆ ಮತ್ತು ಶರಾವತಿ ಪಂಪ್ಡ್ ಸ್ಟೋರೇಜ್ ಯೋಜನೆಯನ್ನು ಅಧಿಕೃತವಾಗಿ ರದ್ದುಗೊಳಿಸಲು ದಾಖಲಿತ ಕ್ಯಾಬಿನೆಟ್ ನಿರ್ಧಾರವನ್ನು ಒದಗಿಸುವಂತೆ ಕಾರ್ಯಕರ್ತರು ಸಚಿವರನ್ನು ಒತ್ತಾಯಿಸಿದರು.",
    category: "Sharavathi Project & Environmental Movement"
  },
  {
    id: 26,
    url: "https://raw.githubusercontent.com/townlinksolutions/townlinksolutions/main/masthappna_naik/images/news/news26.jpg",
    titleEn: "Who is the Deceiver? Accepting the Challenge",
    titleKn: "ವಂಚಕ ಯಾರು? ಸವಾಲನ್ನು ಸ್ವೀಕರಿಸುವುದು",
    shortDescEn: "A major report on Masthappa Naik Balle accepting Minister Mankal Vaidya's challenge to enter politics, titled: \"Who is the Deceiver? Accepting the challenge to bring transparency.\"",
    shortDescKn: "ಮಾಸ್ತಪ್ಪ ನಾಯ್ಕ ಬಲಸೆ ಬಳ್ಳೆ ಅವರು ರಾಜಕೀಯ ಪ್ರವೇಶಿಸಲು ಸಚಿವ ಮಂಕಾಳ ವೈದ್ಯ ಅವರ ಸವಾಲನ್ನು ಸ್ವೀಕರಿಸಿದ ಪ್ರಮುಖ ವರದಿ: \"ವಂಚಕ ಯಾರು? ಪಾರದರ್ಶಕತೆ ತರಲು ಸವಾಲನ್ನು ಸ್ವೀಕರಿಸುವುದು.\"",
    contentEn: "The article covers a high-stakes press conference where Masthappa Naik addressed the personal and political attacks directed at him by the district leadership. <br><br><strong>Key Highlights:</strong><br> <strong>Accepting the Political Challenge:</strong> Under the bold headline \"Who is the Deceiver?\", the report details how Masthappa Naik officially accepted a challenge from District In-charge Minister Mankal Vaidya. Naik stated, \"I accept the challenge and will enter politics to ensure that the voice of the people is heard and that the administration is held accountable.\" <strong>Critique of the Current Leadership:</strong> Naik argued that the current representatives have failed to protect the district's natural resources, particularly the Sharavati River. He criticized the \"Hit and Run\" politics where leaders make accusations but fail to provide administrative solutions. The \"Video War\" <strong>Context:</strong> The report mentions the viral video of Deputy CM D.K. Shivakumar. Naik pointed out the inconsistency between the Minister's public denials and the digital evidence, labeling the Minister's conduct as a betrayal of the public's trust. <strong>Commitment to the Environment:</strong> Despite the political shift, Naik reiterated that the primary mission remains the cancellation of the Sharavati Pumped Storage Project. He pledged that his political entry is a means to achieve an environmental end. <strong>Fighting Digital Misinformation:</strong> He addressed the issue of \"Fake IDs\" being used to \"troll\" and character-assassinate social activists. He called for a cleaner political discourse focused on issues like the ₹50 crore land scam and the lack of doctors in Bhatkal.",
    contentKn: "ಜಿಲ್ಲಾ ನಾಯಕತ್ವವು ತಮ್ಮ ವಿರುದ್ಧ ನಿರ್ದೇಶಿಸಿದ ವೈಯಕ್ತಿಕ ಮತ್ತು ರಾಜಕೀಯ ದಾಳಿಗಳನ್ನು ಮಾಸ್ತಪ್ಪ ನಾಯ್ಕ ಬಲಸೆ ಉದ್ದೇಶಿಸಿ ಮಾತನಾಡಿದ ಹೈ-ಸ್ಟೇಕ್ಸ್ ಪತ್ರಿಕಾಗೋಷ್ಠಿಯನ್ನು ಲೇಖನವು ಒಳಗೊಂಡಿದೆ. <br><br><strong>ಪ್ರಮುಖ ಅಂಶಗಳು:</strong><br> ರಾಜಕೀಯ ಸವಾಲನ್ನು ಸ್ವೀಕರಿಸುವುದು: \"ವಂಚಕ ಯಾರು?\" ಎಂಬ ದಪ್ಪ ತಲೆಬರಹದ ಅಡಿಯಲ್ಲಿ, ಮಾಸ್ತಪ್ಪ ನಾಯ್ಕ ಬಲಸೆ ಅವರು ಜಿಲ್ಲಾ ಉಸ್ತುವಾರಿ ಸಚಿವ ಮಂಕಾಳ ವೈದ್ಯ ಅವರ ಸವಾಲನ್ನು ಅಧಿಕೃತವಾಗಿ ಹೇಗೆ ಸ್ವೀಕರಿಸಿದರು ಎಂಬುದನ್ನು ವರದಿ ವಿವರಿಸುತ್ತದೆ. \"ನಾನು ಸವಾಲನ್ನು ಸ್ವೀಕರಿಸುತ್ತೇನೆ ಮತ್ತು ಜನರ ಧ್ವನಿಯನ್ನು ಕೇಳಲು ಮತ್ತು ಆಡಳಿತವನ್ನು ಹೊಣೆಗಾರರನ್ನಾಗಿ ಮಾಡಲು ರಾಜಕೀಯವನ್ನು ಪ್ರವೇಶಿಸುತ್ತೇನೆ\" ಎಂದು ನಾಯಕ್ ಹೇಳಿದರು. ಪ್ರಸ್ತುತ ನಾಯಕತ್ವದ ಟೀಕೆ: ಪ್ರಸ್ತುತ ಪ್ರತಿನಿಧಿಗಳು ಜಿಲ್ಲೆಯ ನೈಸರ್ಗಿಕ ಸಂಪನ್ಮೂಲಗಳನ್ನು, ವಿಶೇಷವಾಗಿ ಶರಾವತಿ ನದಿಯನ್ನು ರಕ್ಷಿಸುವಲ್ಲಿ ವಿಫಲರಾಗಿದ್ದಾರೆ ಎಂದು ನಾಯಕ್ ವಾದಿಸಿದರು. ನಾಯಕರು ಆರೋಪಗಳನ್ನು ಮಾಡುವ ಆದರೆ ಆಡಳಿತಾತ್ಮಕ ಪರಿಹಾರಗಳನ್ನು ಒದಗಿಸಲು ವಿಫಲರಾಗುವ \"ಹಿಟ್ ಅಂಡ್ ರನ್\" ರಾಜಕೀಯವನ್ನು ಅವರು ಟೀಕಿಸಿದರು. \"ವೀಡಿಯೊ ಯುದ್ಧ\" ಸಂದರ್ಭ: ಉಪಮುಖ್ಯಮಂತ್ರಿ ಡಿ.ಕೆ. ಶಿವಕುಮಾರ್ ಅವರ ವೈರಲ್ ವೀಡಿಯೊವನ್ನು ವರದಿ ಉಲ್ಲೇಖಿಸುತ್ತದೆ. ಸಚಿವರ ಸಾರ್ವಜನಿಕ ನಿರಾಕರಣೆಗಳು ಮತ್ತು ಡಿಜಿಟಲ್ ಪುರಾವೆಗಳ ನಡುವಿನ ಅಸಂಗತತೆಯನ್ನು ನಾಯಕ್ ಬೊಟ್ಟು ಮಾಡಿದರು, ಸಚಿವರ ನಡವಳಿಕೆಯನ್ನು ಸಾರ್ವಜನಿಕರ ನಂಬಿಕೆಯ ದ್ರೋಹ ಎಂದು ಕರೆದರು. ಪರಿಸರಕ್ಕೆ ಬದ್ಧತೆ: ರಾಜಕೀಯ ಬದಲಾವಣೆಯ ಹೊರತಾಗಿಯೂ, ಶರಾವತಿ ಪಂಪ್ಡ್ ಸ್ಟೋರೇಜ್ ಯೋಜನೆಯನ್ನು ರದ್ದುಗೊಳಿಸುವುದು ಪ್ರಾಥಮಿಕ ಉದ್ದೇಶವಾಗಿದೆ ಎಂದು ನಾಯಕ್ ಪುನರುಚ್ಚರಿಸಿದರು. ತಮ್ಮ ರಾಜಕೀಯ ಪ್ರವೇಶವು ಪರಿಸರ ಗುರಿಯನ್ನು ಸಾಧಿಸುವ ಸಾಧನವಾಗಿದೆ ಎಂದು ಅವರು ಪ್ರತಿಜ್ಞೆ ಮಾಡಿದರು. ಡಿಜಿಟಲ್ ತಪ್ಪು ಮಾಹಿತಿಯ ವಿರುದ್ಧ ಹೋರಾಟ: ಸಾಮಾಜಿಕ ಕಾರ್ಯಕರ್ತರನ್ನು \"ಟ್ರೋಲ್\" ಮಾಡಲು ಮತ್ತು ತೇಜೋವಧೆ ಮಾಡಲು \"ನಕಲಿ ಐಡಿಗಳನ್ನು\" ಬಳಸುವ ಸಮಸ್ಯೆಯನ್ನು ಅವರು ಪ್ರಸ್ತಾಪಿಸಿದರು. 50 ಕೋಟಿ ರೂ.ಗಳ ಭೂ ಹಗರಣ ಮತ್ತು ಭಟ್ಕಳದಲ್ಲಿ ವೈದ್ಯರ ಕೊರತೆಯಂತಹ ಸಮಸ್ಯೆಗಳ ಮೇಲೆ ಕೇಂದ್ರೀಕರಿಸಿದ ಸ್ವಚ್ಛ ರಾಜಕೀಯ ಚರ್ಚೆಗೆ ಅವರು ಕರೆ ನೀಡಿದರು.",
    category: "Sharavathi Project & Environmental Movement"
  },
  {
    id: 27,
    url: "https://raw.githubusercontent.com/townlinksolutions/townlinksolutions/main/masthappna_naik/images/news/news27.jpg",
    titleEn: "Fake IDs and Social Media Trolling",
    titleKn: "ನಕಲಿ ಐಡಿಗಳು ಮತ್ತು ಸಾಮಾಜಿಕ ಮಾಧ್ಯಮ ಟ್ರೋಲಿಂಗ್",
    shortDescEn: "A hard-hitting investigative report on the use of Fake IDs and Social Media Trolling to character-assassinate activists, titled: \"Why Are They Like That? Why Are These People Like This?\"",
    shortDescKn: "ಕಾರ್ಯಕರ್ತರ ತೇಜೋವಧೆ ಮಾಡಲು ನಕಲಿ ಐಡಿಗಳು ಮತ್ತು ಸಾಮಾಜಿಕ ಮಾಧ್ಯಮ ಟ್ರೋಲಿಂಗ್ ಬಳಕೆಯ ಕುರಿತಾದ ಕಠಿಣ ತನಿಖಾ ವರದಿ: \"ಅವರು ಏಕೆ ಹಾಗಿದ್ದಾರೆ? ಈ ಜನರು ಏಕೆ ಹೀಗಿದ್ದಾರೆ?\"",
    contentEn: "The article analyzes the deteriorating quality of political discourse in the district, specifically focusing on how digital tools are being weaponized against those who question the current administration. <br><br><strong>Key Highlights:</strong><br> <strong>Weaponization of Social Media:</strong> The headline—\"Fake IDs Used as Weapons to Tarnish Opponents in Bhatkal\"—details a systematic effort to silence social activists. The report alleges that when leaders cannot answer tough questions with facts, they resort to \"digital mobs\" to distract the public. <strong>Targeting Masthappa Naik:</strong> The report explicitly mentions that social activist Masthappa Naik Balle has been a primary target of these \"Hit and Run\" digital attacks. Because of his persistent questioning on the Sharavati Project and the ₹50 crore land scam, fake profiles have been created to spread misinformation about his personal life and motives. \"Fake\" vs. \Fact\: The article critiques the \"troll culture\" where serious administrative lapses are buried under a mountain of fake comments and personal insults. It notes that the truth regarding Deputy CM D.K. Shivakumar's viral video is being obscured by these coordinated digital efforts. <strong>Impact on Democracy:</strong> The report argues that this trend is dangerous for the region's democracy. It warns that if young people are paid to run \"fake ID factories\" to protect politicians, the real issues—like the lack of specialist doctors and environmental destruction—will never be resolved. <strong>A Call for Dignity:</strong> The article concludes by urging the people of Uttara Kannada not to believe everything they see on social media and to support leaders who are willing to debate issues face-to-face rather than behind anonymous screens.",
    contentKn: "ಲೇಖನವು ಜಿಲ್ಲೆಯಲ್ಲಿ ರಾಜಕೀಯ ಚರ್ಚೆಯ ಹದಗೆಡುತ್ತಿರುವ ಗುಣಮಟ್ಟವನ್ನು ವಿಶ್ಲೇಷಿಸುತ್ತದೆ, ನಿರ್ದಿಷ್ಟವಾಗಿ ಪ್ರಸ್ತುತ ಆಡಳಿತವನ್ನು ಪ್ರಶ್ನಿಸುವವರ ವಿರುದ್ಧ ಡಿಜಿಟಲ್ ಸಾಧನಗಳನ್ನು ಹೇಗೆ ಅಸ್ತ್ರವಾಗಿ ಬಳಸಲಾಗುತ್ತಿದೆ ಎಂಬುದರ ಮೇಲೆ ಕೇಂದ್ರೀಕರಿಸುತ್ತದೆ. <br><br><strong>ಪ್ರಮುಖ ಅಂಶಗಳು:</strong><br> ಸಾಮಾಜಿಕ ಮಾಧ್ಯಮದ ಅಸ್ತ್ರೀಕರಣ: \"ಭಟ್ಕಳದಲ್ಲಿ ವಿರೋಧಿಗಳನ್ನು ಕಳಂಕಗೊಳಿಸಲು ನಕಲಿ ಐಡಿಗಳನ್ನು ಅಸ್ತ್ರವಾಗಿ ಬಳಸಲಾಗುತ್ತದೆ\" ಎಂಬ ತಲೆಬರಹವು ಸಾಮಾಜಿಕ ಕಾರ್ಯಕರ್ತರನ್ನು ಮೌನಗೊಳಿಸುವ ವ್ಯವಸ್ಥಿತ ಪ್ರಯತ್ನವನ್ನು ವಿವರಿಸುತ್ತದೆ. ನಾಯಕರು ಕಠಿಣ ಪ್ರಶ್ನೆಗಳಿಗೆ ಸತ್ಯಗಳೊಂದಿಗೆ ಉತ್ತರಿಸಲು ಸಾಧ್ಯವಾಗದಿದ್ದಾಗ, ಸಾರ್ವಜನಿಕರ ಗಮನವನ್ನು ಬೇರೆಡೆ ಸೆಳೆಯಲು ಅವರು \"ಡಿಜಿಟಲ್ ಗುಂಪುಗಳನ್ನು\" ಆಶ್ರಯಿಸುತ್ತಾರೆ ಎಂದು ವರದಿ ಆರೋಪಿಸುತ್ತದೆ. ಮಾಸ್ತಪ್ಪ ನಾಯಕ್ ಅವರನ್ನು ಗುರಿಯಾಗಿಸುವುದು: ಸಾಮಾಜಿಕ ಕಾರ್ಯಕರ್ತ ಮಾಸ್ತಪ್ಪ ನಾಯಕ್ ಬಳ್ಳೆ ಅವರು ಈ \"ಹಿಟ್ ಅಂಡ್ ರನ್\" ಡಿಜಿಟಲ್ ದಾಳಿಯ ಪ್ರಾಥಮಿಕ ಗುರಿಯಾಗಿದ್ದಾರೆ ಎಂದು ವರದಿ ಸ್ಪಷ್ಟವಾಗಿ ಉಲ್ಲೇಖಿಸುತ್ತದೆ. ಶರಾವತಿ ಯೋಜನೆ ಮತ್ತು 50 ಕೋಟಿ ರೂ.ಗಳ ಭೂ ಹಗರಣದ ಬಗ್ಗೆ ಅವರ ನಿರಂತರ ಪ್ರಶ್ನೆಯಿಂದಾಗಿ, ಅವರ ವೈಯಕ್ತಿಕ ಜೀವನ ಮತ್ತು ಉದ್ದೇಶಗಳ ಬಗ್ಗೆ ತಪ್ಪು ಮಾಹಿತಿಯನ್ನು ಹರಡಲು ನಕಲಿ ಪ್ರೊಫೈಲ್‌ಗಳನ್ನು ರಚಿಸಲಾಗಿದೆ. \"ನಕಲಿ\" ವಿರುದ್ಧ \ಸತ್ಯ\: ಗಂಭೀರ ಆಡಳಿತಾತ್ಮಕ ಲೋಪಗಳನ್ನು ನಕಲಿ ಕಾಮೆಂಟ್‌ಗಳು ಮತ್ತು ವೈಯಕ್ತಿಕ ಅವಮಾನಗಳ ಪರ್ವತದ ಅಡಿಯಲ್ಲಿ ಹೂಳಲಾಗಿರುವ \"ಟ್ರೋಲ್ ಸಂಸ್ಕೃತಿಯನ್ನು\" ಲೇಖನವು ಟೀಕಿಸುತ್ತದೆ. ಉಪಮುಖ್ಯಮಂತ್ರಿ ಡಿ.ಕೆ. ಶಿವಕುಮಾರ್ ಅವರ ವೈರಲ್ ವೀಡಿಯೊಗೆ ಸಂಬಂಧಿಸಿದ ಸತ್ಯವನ್ನು ಈ ಸಂಘಟಿತ ಡಿಜಿಟಲ್ ಪ್ರಯತ್ನಗಳಿಂದ ಮರೆಮಾಡಲಾಗುತ್ತಿದೆ ಎಂದು ಅದು ಗಮನಿಸುತ್ತದೆ. ಪ್ರಜಾಪ್ರಭುತ್ವದ ಮೇಲಿನ ಪ್ರಭಾವ: ಈ ಪ್ರವೃತ್ತಿಯು ಪ್ರದೇಶದ ಪ್ರಜಾಪ್ರಭುತ್ವಕ್ಕೆ ಅಪಾಯಕಾರಿ ಎಂದು ವರದಿ ವಾದಿಸುತ್ತದೆ. ರಾಜಕಾರಣಿಗಳನ್ನು ರಕ್ಷಿಸಲು ಯುವಕರಿಗೆ \"ನಕಲಿ ಐಡಿ ಕಾರ್ಖಾನೆಗಳನ್ನು\" ನಡೆಸಲು ಹಣ ನೀಡಿದರೆ, ತಜ್ಞ ವೈದ್ಯರ ಕೊರತೆ ಮತ್ತು ಪರಿಸರ ನಾಶದಂತಹ ನೈಜ ಸಮಸ್ಯೆಗಳು ಎಂದಿಗೂ ಪರಿಹರಿಸಲ್ಪಡುವುದಿಲ್ಲ ಎಂದು ಅದು ಎಚ್ಚರಿಸುತ್ತದೆ. ಘನತೆಗಾಗಿ ಕರೆ: ಸಾಮಾಜಿಕ ಮಾಧ್ಯಮದಲ್ಲಿ ನೋಡುವ ಎಲ್ಲವನ್ನೂ ನಂಬಬೇಡಿ ಮತ್ತು ಅನಾಮಧೇಯ ಪರದೆಗಳ ಹಿಂದಿನ ಬದಲು ಮುಖಾಮುಖಿಯಾಗಿ ಸಮಸ್ಯೆಗಳನ್ನು ಚರ್ಚಿಸಲು ಸಿದ್ಧರಿರುವ ನಾಯಕರನ್ನು ಬೆಂಬಲಿಸುವಂತೆ ಉತ್ತರ ಕನ್ನಡದ ಜನರನ್ನು ಒತ್ತಾಯಿಸುವ ಮೂಲಕ ಲೇಖನವು ಮುಕ್ತಾಯಗೊಳ್ಳುತ್ತದೆ.",
    category: "Sharavathi Project & Environmental Movement"
  },
  {
    id: 28,
    url: "https://raw.githubusercontent.com/townlinksolutions/townlinksolutions/main/masthappna_naik/images/news/news28.jpg",
    titleEn: "Masthappa Naik Counters Minister Mankal Vaidya on Sharavati Project",
    titleKn: "ಶರಾವತಿ ಯೋಜನೆ ಕುರಿತು ಸಚಿವ ಮಂಕಾಳ ವೈದ್ಯರ ಹೇಳಿಕೆಗೆ ಮಾಸ್ತಪ್ಪ ನಾಯ್ಕ ಬಲಸೆ ತಿರುಗೇಟು",
    shortDescEn: "Social activist Masthappa Naik has strongly countered Minister Mankal Vaidya’s claims regarding the Sharavati Pumped Storage Project. During a press conference, Naik criticized the Minister's alleged inaction during the project's early stages and demanded a public apology from the government for moving forward with it.",
    shortDescKn: "ಶರಾವತಿ ಪಂಪ್ಡ್ ಸ್ಟೋರೇಜ್ ಯೋಜನೆ ಕುರಿತು ಸಚಿವ ಮಂಕಾಳ ವೈದ್ಯರ ಹೇಳಿಕೆಯನ್ನು ಸಾಮಾಜಿಕ ಕಾರ್ಯಕರ್ತ ಮಾಸ್ತಪ್ಪ ನಾಯ್ಕ ಬಲಸೆ ಬಲವಾಗಿ ವಿರೋಧಿಸಿದ್ದಾರೆ. ಪತ್ರಿಕಾಗೋಷ್ಠಿಯಲ್ಲಿ ಮಾತನಾಡಿದ ನಾಯ್ಕ್, ಯೋಜನೆಯ ಆರಂಭಿಕ ಹಂತಗಳಲ್ಲಿ ಸಚಿವರ ನಿಷ್ಕ್ರಿಯತೆಯನ್ನು ಟೀಕಿಸಿದರು ಮತ್ತು ಯೋಜನೆಯನ್ನು ಮುಂದುವರಿಸಿದ್ದಕ್ಕಾಗಿ ಸರ್ಕಾರ ಸಾರ್ವಜನಿಕವಾಗಿ ಕ್ಷಮೆಯಾಚಿಸಬೇಕೆಂದು ಒತ್ತಾಯಿಸಿದರು.",
    contentEn: "The Conflict: The report highlights a \"rebuttal\" by Masthappa Naik to Minister Mankal Vaidya. The Minister had previously claimed that Deputy CM D.K. Shivakumar had not spoken about the project, which Naik disputes.\n\nSymbolic Protest: In a notable moment captured in the photo, Naik held up a bottle of coconut oil. He sarcastically suggested that the Minister should use it to \"clear his ears,\" implying that the Minister is intentionally ignoring the facts or the voices of the people despite being able to hear.\n\nHistorical Context provided by Naik:\n2016: Naik claims the Congress government assigned a private company to prepare the Detailed Project Report (DPR) on May 13, 2016. He questioned why Vaidya, who was an MLA then, did not oppose it at that stage.\n2023: He noted that the BJP government released ₹1,000 crores for the project.\n\nCurrent Status: The current Congress government has approved a grant for 2,000 MW power generation.\n\nDemands: Masthappa Naik demanded that the Minister and the Block Congress President apologize to the farmers and the public for the project's progression.\n\nProject Context: The Sharavati Pumped Storage Project is a major hydroelectric initiative that has faced significant local opposition due to environmental concerns and its impact on the local ecosystem in the Western Ghats.",
    contentKn: "ಸಂಘರ್ಷ: ಸಚಿವ ಮಂಕಾಳ ವೈದ್ಯ ಅವರು ಈ ಹಿಂದೆ ಉಪಮುಖ್ಯಮಂತ್ರಿ ಡಿ.ಕೆ. ಶಿವಕುಮಾರ್ ಅವರು ಈ ಯೋಜನೆಯ ಬಗ್ಗೆ ಮಾತನಾಡಿಲ್ಲ ಎಂದು ಹೇಳಿದ್ದರು, ಇದನ್ನು ಮಾಸ್ತಪ್ಪ ನಾಯ್ಕ ಬಲಸೆ ವಿರೋಧಿಸಿದ್ದಾರೆ.\n\nಸಾಂಕೇತಿಕ ಪ್ರತಿಭಟನೆ: ಫೋಟೋದಲ್ಲಿ ಸೆರೆಹಿಡಿಯಲಾದ ಗಮನಾರ್ಹ ಕ್ಷಣದಲ್ಲಿ, ನಾಯ್ಕ್ ತೆಂಗಿನೆಣ್ಣೆಯ ಬಾಟಲಿಯನ್ನು ಹಿಡಿದಿದ್ದರು. ಸಚಿವರು ಕೇಳಿಸಿಕೊಳ್ಳಬಲ್ಲವರಾಗಿದ್ದರೂ ಸತ್ಯವನ್ನು ಅಥವಾ ಜನರ ಧ್ವನಿಯನ್ನು ಉದ್ದೇಶಪೂರ್ವಕವಾಗಿ ನಿರ್ಲಕ್ಷಿಸುತ್ತಿದ್ದಾರೆ ಎಂದು ಸೂಚಿಸಲು, ಅವರು ಅದನ್ನು \"ಕಿವಿ ಸ್ವಚ್ಛಗೊಳಿಸಲು\" ಬಳಸಬೇಕೆಂದು ವ್ಯಂಗ್ಯವಾಗಿ ಸಲಹೆ ನೀಡಿದರು.\n\nನಾಯ್ಕ್ ಒದಗಿಸಿದ ಐತಿಹಾಸಿಕ ಹಿನ್ನೆಲೆ:\n2016: ಮೇ 13, 2016 ರಂದು ಕಾಂಗ್ರೆಸ್ ಸರ್ಕಾರವು ವಿವರವಾದ ಯೋಜನಾ ವರದಿಯನ್ನು (DPR) ತಯಾರಿಸಲು ಖಾಸಗಿ ಕಂಪನಿಯನ್ನು ನೇಮಿಸಿತು ಎಂದು ನಾಯ್ಕ್ ಹೇಳಿದ್ದಾರೆ. ಆಗ ಶಾಸಕರಾಗಿದ್ದ ವೈದ್ಯರು ಆ ಹಂತದಲ್ಲಿ ಏಕೆ ವಿರೋಧಿಸಲಿಲ್ಲ ಎಂದು ಅವರು ಪ್ರಶ್ನಿಸಿದರು.\n2023: ಬಿಜೆಪಿ ಸರ್ಕಾರವು ಯೋಜನೆಗಾಗಿ ₹1,000 ಕೋಟಿ ಬಿಡುಗಡೆ ಮಾಡಿದೆ ಎಂದು ಅವರು ಗಮನಸೆಳೆದರು.\n\nಪ್ರಸ್ತುತ ಸ್ಥಿತಿ: ಪ್ರಸ್ತುತ ಕಾಂಗ್ರೆಸ್ ಸರ್ಕಾರವು 2,000 ಮೆಗಾವ್ಯಾಟ್ ವಿದ್ಯುತ್ ಉತ್ಪಾದನೆಗೆ ಅನುದಾನವನ್ನು ಅನುಮೋದಿಸಿದೆ.\n\nಬೇಡಿಕೆಗಳು: ಯೋಜನೆಯ ಪ್ರಗತಿಗಾಗಿ ಸಚಿವರು ಮತ್ತು ಬ್ಲಾಕ್ ಕಾಂಗ್ರೆಸ್ ಅಧ್ಯಕ್ಷರು ರೈತರು ಮತ್ತು ಸಾರ್ವಜನಿಕರಲ್ಲಿ ಕ್ಷಮೆಯಾಚಿಸಬೇಕೆಂದು ಮಾಸ್ತಪ್ಪ ನಾಯ್ಕ ಬಲಸೆ ಒತ್ತಾಯಿಸಿದರು.\n\nಯೋಜನೆಯ ಹಿನ್ನೆಲೆ: ಶರಾವತಿ ಪಂಪ್ಡ್ ಸ್ಟೋರೇಜ್ ಯೋಜನೆಯು ಪ್ರಮುಖ ಜಲವಿದ್ಯುತ್ ಯೋಜನೆಯಾಗಿದ್ದು, ಪರಿಸರ ಕಾಳಜಿ ಮತ್ತು ಪಶ್ಚಿಮ ಘಟ್ಟಗಳ ಸ್ಥಳೀಯ ಪರಿಸರ ವ್ಯವಸ್ಥೆಯ ಮೇಲೆ ಬೀರುವ ಪರಿಣಾಮದಿಂದಾಗಿ ಸ್ಥಳೀಯವಾಗಿ ತೀವ್ರ ವಿರೋಧವನ್ನು ಎದುರಿಸುತ್ತಿದೆ.",
    category: "Youth Lead"
  },
  {
    id: 29,
    url: "https://raw.githubusercontent.com/townlinksolutions/townlinksolutions/main/masthappna_naik/images/news/news29.jpg",
    titleEn: "Masthappa Naik Addresses Press Meet on Governance and Accountability",
    titleKn: "ಆಡಳಿತ ಮತ್ತು ಹೊಣೆಗಾರಿಕೆಯ ಕುರಿತು ಮಾಸ್ತಪ್ಪ ನಾಯ್ಕ ಬಲಸೆ ಅವರ ಪತ್ರಿಕಾಗೋಷ್ಠಿ",
    shortDescEn: "Masthappa Naik raises a strong voice against injustice, emphasizing accountability, public welfare, and responsible governance.",
    shortDescKn: "ಅನ್ಯಾಯದ ವಿರುದ್ಧ ಮಾಸ್ತಪ್ಪ ನಾಯ್ಕ ಬಲಸೆ ಅವರ ಬಲವಾದ ಧ್ವನಿ, ಹೊಣೆಗಾರಿಕೆ, ಸಾರ್ವಜನಿಕ ಕಲ್ಯಾಣ ಮತ್ತು ಜವಾಬ್ದಾರಿಯುತ ಆಡಳಿತಕ್ಕೆ ಒತ್ತು ನೀಡಿದ್ದಾರೆ.",
    contentEn: "In this media coverage, Masthappa Naik is seen addressing a press meet where he spoke firmly on issues concerning public welfare and administrative accountability. He highlighted key concerns affecting people at the grassroots level and called for immediate and transparent action from the authorities.\n\nDuring his address, he questioned lapses in governance and stressed the need for responsible leadership that prioritizes citizens’ needs. His speech reflected a proactive approach towards resolving public issues and ensuring justice.\n\nThe presence of supporters and leaders at the event further signifies the growing trust and influence he holds among the people. Through such public interactions and media engagements, Masthappa Naik continues to position himself as a strong advocate for fairness, development, and people-centric governance.",
    contentKn: "ಈ ಮಾಧ್ಯಮ ವರದಿಯಲ್ಲಿ, ಮಾಸ್ತಪ್ಪ ನಾಯ್ಕ ಬಲಸೆ ಅವರು ಪತ್ರಿಕಾಗೋಷ್ಠಿಯನ್ನು ಉದ್ದೇಶಿಸಿ ಮಾತನಾಡುತ್ತಿರುವುದನ್ನು ಕಾಣಬಹುದು, ಅಲ್ಲಿ ಅವರು ಸಾರ್ವಜನಿಕ ಕಲ್ಯಾಣ ಮತ್ತು ಆಡಳಿತಾತ್ಮಕ ಹೊಣೆಗಾರಿಕೆಗೆ ಸಂಬಂಧಿಸಿದ ವಿಷಯಗಳ ಬಗ್ಗೆ ದೃಢವಾಗಿ ಮಾತನಾಡಿದರು. ಅವರು ತಳಮಟ್ಟದಲ್ಲಿ ಜನರನ್ನು ಬಾಧಿಸುತ್ತಿರುವ ಪ್ರಮುಖ ಕಾಳಜಿಗಳನ್ನು ಎತ್ತಿ ತೋರಿಸಿದರು ಮತ್ತು ಅಧಿಕಾರಿಗಳಿಂದ ತಕ್ಷಣದ ಮತ್ತು ಪಾರದರ್ಶಕ ಕ್ರಮಕ್ಕೆ ಕರೆ ನೀಡಿದರು.\n\nತಮ್ಮ ಭಾಷಣದ ಸಂದರ್ಭದಲ್ಲಿ, ಅವರು ಆಡಳಿತದಲ್ಲಿನ ಲೋಪದೋಷಗಳನ್ನು ಪ್ರಶ್ನಿಸಿದರು ಮತ್ತು ನಾಗರಿಕರ ಅಗತ್ಯಗಳಿಗೆ ಆದ್ಯತೆ ನೀಡುವ ಜವಾಬ್ದಾರಿಯುತ ನಾಯಕತ್ವದ ಅಗತ್ಯವನ್ನು ಒತ್ತಿ ಹೇಳಿದರು. ಅವರ ಭಾಷಣವು ಸಾರ್ವಜನಿಕ ಸಮಸ್ಯೆಗಳನ್ನು ಪರಿಹರಿಸುವ ಮತ್ತು ನ್ಯಾಯವನ್ನು ಖಾತ್ರಿಪಡಿಸುವ ಕಡೆಗೆ ಪೂರ್ವಭಾವಿ ವಿಧಾನವನ್ನು ಪ್ರತಿಬಿಂಬಿಸಿತು.\n\nಕಾರ್ಯಕ್ರಮದಲ್ಲಿ ಬೆಂಬಲಿಗರು ಮತ್ತು ನಾಯಕರ ಉಪಸ್ಥಿತಿಯು ಜನರ ನಡುವೆ ಅವರು ಹೊಂದಿರುವ ಬೆಳೆಯುತ್ತಿರುವ ನಂಬಿಕೆ ಮತ್ತು ಪ್ರಭಾವವನ್ನು ಮತ್ತಷ್ಟು ಸೂಚಿಸುತ್ತದೆ. ಇಂತಹ ಸಾರ್ವಜನಿಕ ಸಂವಹನಗಳು ಮತ್ತು ಮಾಧ್ಯಮ ಕಾರ್ಯಕ್ರಮಗಳ ಮೂಲಕ, ಮಾಸ್ತಪ್ಪ ನಾಯ್ಕ ಬಲಸೆ ಅವರು ನ್ಯಾಯ, ಅಭಿವೃದ್ಧಿ ಮತ್ತು ಜನಕೇಂದ್ರಿತ ಆಡಳಿತಕ್ಕಾಗಿ ಬಲವಾದ ವಕೀಲರಾಗಿ ತಮ್ಮನ್ನು ತಾವು ಪ್ರತಿಪಾದಿಸುವುದನ್ನು ಮುಂದುವರಿಸಿದ್ದಾರೆ.",
    category: "Justice & Anti-Corruption Stand"
  },
  {
    id: 30,
    url: "https://raw.githubusercontent.com/townlinksolutions/townlinksolutions/main/masthappna_naik/images/news/news30.jpg",
    titleEn: "Masthappa Naik Advocates for Constitutional Values and Inclusive Governance",
    titleKn: "ಸಾಂವಿಧಾನಿಕ ಮೌಲ್ಯಗಳು ಮತ್ತು ಅಂತರ್ಗತ ಆಡಳಿತಕ್ಕಾಗಿ ಮಾಸ್ತಪ್ಪ ನಾಯ್ಕ ಬಲಸೆ ಅವರ ಪ್ರತಿಪಾದನೆ",
    shortDescEn: "A strong political voice advocating constitutional values and inclusive governance, Masthappa Naik continues to address public concerns with clarity, courage, and commitment.",
    shortDescKn: "ಸಾಂವಿಧಾನಿಕ ಮೌಲ್ಯಗಳು ಮತ್ತು ಅಂತರ್ಗತ ಆಡಳಿತವನ್ನು ಪ್ರತಿಪಾದಿಸುವ ಬಲವಾದ ರಾಜಕೀಯ ಧ್ವನಿ, ಮಾಸ್ತಪ್ಪ ನಾಯ್ಕ ಬಲಸೆ ಅವರು ಸ್ಪಷ್ಟತೆ, ಧೈರ್ಯ ಮತ್ತು ಬದ್ಧತೆಯೊಂದಿಗೆ ಸಾರ್ವಜನಿಕ ಕಾಳಜಿಗಳನ್ನು ತಿಳಿಸುವುದನ್ನು ಮುಂದುವರಿಸಿದ್ದಾರೆ.",
    contentEn: "Masthappa Naik has emerged as a prominent public leader known for his impactful speeches and grassroots connection with the people. As highlighted in the featured news coverage, he strongly emphasized the importance of constitutional values, social justice, and transparent governance while addressing a public gathering.\n\nDuring the event, he spoke about key societal and political issues, urging leaders and citizens alike to uphold democratic principles and work towards equitable development. His speech reflected a deep concern for the welfare of marginalized communities and the need for accountable leadership.\n\nThe gathering witnessed active public participation, showcasing the growing support for his vision and leadership. Through such engagements, Masthappa Naik continues to inspire dialogue, awareness, and collective responsibility among people.",
    contentKn: "ಮಾಸ್ತಪ್ಪ ನಾಯ್ಕ ಬಲಸೆ ಅವರು ತಮ್ಮ ಪ್ರಭಾವಶಾಲಿ ಭಾಷಣಗಳು ಮತ್ತು ಜನರೊಂದಿಗೆ ತಳಮಟ್ಟದ ಸಂಪರ್ಕಕ್ಕಾಗಿ ಹೆಸರುವಾಸಿಯಾದ ಪ್ರಮುಖ ಸಾರ್ವಜನಿಕ ನಾಯಕರಾಗಿ ಹೊರಹೊಮ್ಮಿದ್ದಾರೆ. ವೈಶಿಷ್ಟ್ಯಗೊಳಿಸಿದ ಸುದ್ದಿ ವರದಿಯಲ್ಲಿ ಎತ್ತಿ ತೋರಿಸಿದಂತೆ, ಸಾರ್ವಜನಿಕ ಸಭೆಯನ್ನು ಉದ್ದೇಶಿಸಿ ಮಾತನಾಡುತ್ತಾ ಅವರು ಸಾಂವಿಧಾನಿಕ ಮೌಲ್ಯಗಳು, ಸಾಮಾಜಿಕ ನ್ಯಾಯ ಮತ್ತು ಪಾರದರ್ಶಕ ಆಡಳಿತದ ಮಹತ್ವವನ್ನು ಬಲವಾಗಿ ಒತ್ತಿ ಹೇಳಿದರು.\n\nಕಾರ್ಯಕ್ರಮದ ಸಂದರ್ಭದಲ್ಲಿ, ಅವರು ಪ್ರಮುಖ ಸಾಮಾಜಿಕ ಮತ್ತು ರಾಜಕೀಯ ವಿಷಯಗಳ ಬಗ್ಗೆ ಮಾತನಾಡಿದರು, ನಾಯಕರು ಮತ್ತು ನಾಗರಿಕರು ಇಬ್ಬರೂ ಪ್ರಜಾಪ್ರಭುತ್ವದ ತತ್ವಗಳನ್ನು ಎತ್ತಿಹಿಡಿಯಲು ಮತ್ತು ಸಮಾನ ಅಭಿವೃದ್ಧಿಯತ್ತ ಕೆಲಸ ಮಾಡಲು ಒತ್ತಾಯಿಸಿದರು. ಅವರ ಭಾಷಣವು ಅಂಚಿನಲ್ಲಿರುವ ಸಮುದಾಯಗಳ ಕಲ್ಯಾಣ ಮತ್ತು ಜವಾಬ್ದಾರಿಯುತ ನಾಯಕತ್ವದ ಅಗತ್ಯತೆಯ ಬಗ್ಗೆ ಆಳವಾದ ಕಾಳಜಿಯನ್ನು ಪ್ರತಿಬಿಂಬಿಸಿತು.\n\nಈ ಸಭೆಯು ಸಕ್ರಿಯ ಸಾರ್ವಜನಿಕ ಭಾಗವಹಿಸುವಿಕೆಗೆ ಸಾಕ್ಷಿಯಾಯಿತು, ಇದು ಅವರ ದೃಷ್ಟಿ ಮತ್ತು ನಾಯಕತ್ವಕ್ಕೆ ಬೆಳೆಯುತ್ತಿರುವ ಬೆಂಬಲವನ್ನು ಪ್ರದರ್ಶಿಸಿತು. ಇಂತಹ ಕಾರ್ಯಕ್ರಮಗಳ ಮೂಲಕ, ಮಾಸ್ತಪ್ಪ ನಾಯ್ಕ ಬಲಸೆ ಅವರು ಜನರ ನಡುವೆ ಸಂವಾದ, ಜಾಗೃತಿ ಮತ್ತು ಸಾಮೂಹಿಕ ಜವಾಬ್ದಾರಿಯನ್ನು ಪ್ರೇರೇಪಿಸುವುದನ್ನು ಮುಂದುವರಿಸಿದ್ದಾರೆ.",
    category: "Organizational Growth"
  }
];

if (typeof window !== 'undefined') {
  window.newsItems = newsItems;
}

if (typeof module !== 'undefined' && module.exports) {
  module.exports = newsItems;
}

